// @generated by `bun run build` in crates/runtime/js — do not edit by hand.
// serialization/protobuf/lexer.ts
var IDENT_START = /[A-Za-z_]/;
var IDENT_PART = /[A-Za-z0-9_]/;
var DIGIT = /[0-9]/;

class Lexer {
  src;
  pos = 0;
  line = 1;
  peeked = null;
  constructor(src) {
    this.src = src;
  }
  peek() {
    return this.peeked ??= this.scan();
  }
  next() {
    if (this.peeked) {
      const t = this.peeked;
      this.peeked = null;
      return t;
    }
    return this.scan();
  }
  scan() {
    this.skipTrivia();
    if (this.pos >= this.src.length)
      return { kind: "eof", value: "", line: this.line };
    const ch = this.src[this.pos];
    const line = this.line;
    if (IDENT_START.test(ch)) {
      const start = this.pos;
      while (this.pos < this.src.length && IDENT_PART.test(this.src[this.pos]))
        this.pos++;
      return { kind: "ident", value: this.src.slice(start, this.pos), line };
    }
    if (DIGIT.test(ch) || ch === "." && DIGIT.test(this.src[this.pos + 1] ?? "")) {
      return { kind: "num", value: this.scanNumber(), line };
    }
    if (ch === '"' || ch === "'") {
      return { kind: "str", value: this.scanString(ch), line };
    }
    this.pos++;
    return { kind: "sym", value: ch, line };
  }
  scanNumber() {
    const start = this.pos;
    if (this.src[this.pos] === "0" && (this.src[this.pos + 1] === "x" || this.src[this.pos + 1] === "X")) {
      this.pos += 2;
      while (this.pos < this.src.length && /[0-9a-fA-F]/.test(this.src[this.pos]))
        this.pos++;
      return this.src.slice(start, this.pos);
    }
    while (this.pos < this.src.length && /[0-9.eE+\-]/.test(this.src[this.pos])) {
      const c = this.src[this.pos];
      if ((c === "+" || c === "-") && !/[eE]/.test(this.src[this.pos - 1] ?? ""))
        break;
      this.pos++;
    }
    return this.src.slice(start, this.pos);
  }
  scanString(quote) {
    this.pos++;
    let out = "";
    while (this.pos < this.src.length) {
      const c = this.src[this.pos++];
      if (c === quote)
        return out;
      if (c === "\\") {
        const e = this.src[this.pos++];
        switch (e) {
          case "n":
            out += `
`;
            break;
          case "r":
            out += "\r";
            break;
          case "t":
            out += "\t";
            break;
          case "\\":
            out += "\\";
            break;
          case '"':
            out += '"';
            break;
          case "'":
            out += "'";
            break;
          case "0":
            out += "\x00";
            break;
          default:
            out += e;
            break;
        }
      } else {
        if (c === `
`)
          this.line++;
        out += c;
      }
    }
    throw new Error(`protobuf: unterminated string at line ${this.line}`);
  }
  skipTrivia() {
    while (this.pos < this.src.length) {
      const c = this.src[this.pos];
      if (c === `
`) {
        this.line++;
        this.pos++;
      } else if (c === " " || c === "\t" || c === "\r" || c === "\f" || c === "\v") {
        this.pos++;
      } else if (c === "/" && this.src[this.pos + 1] === "/") {
        while (this.pos < this.src.length && this.src[this.pos] !== `
`)
          this.pos++;
      } else if (c === "/" && this.src[this.pos + 1] === "*") {
        this.pos += 2;
        while (this.pos < this.src.length && !(this.src[this.pos] === "*" && this.src[this.pos + 1] === "/")) {
          if (this.src[this.pos] === `
`)
            this.line++;
          this.pos++;
        }
        this.pos += 2;
      } else {
        break;
      }
    }
  }
}

// serialization/protobuf/features.ts
function baseFeatures(syntax) {
  if (syntax === "proto2") {
    return { fieldPresence: "EXPLICIT", repeatedEncoding: "EXPANDED", enumType: "CLOSED", messageEncoding: "LENGTH_PREFIXED" };
  }
  if (syntax === "proto3") {
    return { fieldPresence: "IMPLICIT", repeatedEncoding: "PACKED", enumType: "OPEN", messageEncoding: "LENGTH_PREFIXED" };
  }
  return { fieldPresence: "EXPLICIT", repeatedEncoding: "PACKED", enumType: "OPEN", messageEncoding: "LENGTH_PREFIXED" };
}
function mergeFeatures(base, over) {
  if (!over)
    return base;
  return {
    fieldPresence: over.fieldPresence ?? base.fieldPresence,
    repeatedEncoding: over.repeatedEncoding ?? base.repeatedEncoding,
    enumType: over.enumType ?? base.enumType,
    messageEncoding: over.messageEncoding ?? base.messageEncoding
  };
}
function featureFromOption(key, value) {
  switch (key) {
    case "features.field_presence":
      return { fieldPresence: value };
    case "features.repeated_field_encoding":
      return { repeatedEncoding: value };
    case "features.enum_type":
      return { enumType: value };
    case "features.message_encoding":
      return { messageEncoding: value };
    default:
      return null;
  }
}

// serialization/protobuf/parser.ts
var SCALARS = new Set([
  "double",
  "float",
  "int32",
  "int64",
  "uint32",
  "uint64",
  "sint32",
  "sint64",
  "fixed32",
  "fixed64",
  "sfixed32",
  "sfixed64",
  "bool",
  "string",
  "bytes"
]);
function parseProto(source) {
  return new Parser(source).parseFile();
}

class Parser {
  lx;
  syntax = "proto3";
  constructor(source) {
    this.lx = new Lexer(source);
  }
  err(msg, line) {
    throw new Error(`protobuf parse error${line ? ` (line ${line})` : ""}: ${msg}`);
  }
  expectSym(s) {
    const t = this.lx.next();
    if (t.kind !== "sym" || t.value !== s)
      this.err(`expected '${s}', got '${t.value}'`, t.line);
  }
  acceptSym(s) {
    const t = this.lx.peek();
    if (t.kind === "sym" && t.value === s) {
      this.lx.next();
      return true;
    }
    return false;
  }
  expectIdent() {
    const t = this.lx.next();
    if (t.kind !== "ident")
      this.err(`expected identifier, got '${t.value}'`, t.line);
    return t.value;
  }
  isKeyword(t, kw) {
    return t.kind === "ident" && t.value === kw;
  }
  parseFile() {
    const file = {
      syntax: "proto3",
      package: "",
      imports: [],
      features: {},
      messages: [],
      enums: []
    };
    let sawSyntax = false;
    for (;; ) {
      const t = this.lx.peek();
      if (t.kind === "eof")
        break;
      if (t.kind === "sym" && t.value === ";") {
        this.lx.next();
        continue;
      }
      if (t.kind !== "ident")
        this.err(`unexpected '${t.value}'`, t.line);
      switch (t.value) {
        case "syntax": {
          this.lx.next();
          this.expectSym("=");
          const v = this.expectStr();
          if (v !== "proto3" && v !== "proto2")
            this.err(`unknown syntax "${v}"`, t.line);
          file.syntax = v;
          this.syntax = v;
          this.expectSym(";");
          sawSyntax = true;
          break;
        }
        case "edition": {
          this.lx.next();
          this.expectSym("=");
          const v = this.expectStr();
          if (v !== "2023" && v !== "2024")
            this.err(`unsupported edition "${v}" (only 2023, 2024)`, t.line);
          file.syntax = v;
          this.syntax = v;
          this.expectSym(";");
          sawSyntax = true;
          break;
        }
        case "package":
          this.lx.next();
          file.package = this.parseQualifiedName();
          this.expectSym(";");
          break;
        case "import": {
          this.lx.next();
          const p = this.lx.peek();
          if (this.isKeyword(p, "public") || this.isKeyword(p, "weak"))
            this.lx.next();
          file.imports.push(this.expectStr());
          this.expectSym(";");
          break;
        }
        case "option": {
          this.lx.next();
          const { key, value } = this.parseOption();
          const f = featureFromOption(key, value);
          if (f)
            Object.assign(file.features, f);
          this.expectSym(";");
          break;
        }
        case "message":
          this.lx.next();
          file.messages.push(this.parseMessage());
          break;
        case "enum":
          this.lx.next();
          file.enums.push(this.parseEnum());
          break;
        case "service":
          this.lx.next();
          this.skipBlock();
          break;
        case "extend":
          this.lx.next();
          this.skipBlock();
          break;
        default:
          this.err(`unexpected '${t.value}' at top level`, t.line);
      }
    }
    return file;
  }
  parseMessage() {
    return this.parseMessageBody(this.expectIdent());
  }
  parseMessageBody(name) {
    const msg = { name, fields: [], oneofs: [], messages: [], enums: [], features: {} };
    this.expectSym("{");
    for (;; ) {
      const t = this.lx.peek();
      if (t.kind === "sym" && t.value === "}") {
        this.lx.next();
        break;
      }
      if (t.kind === "eof")
        this.err("unexpected EOF in message");
      if (t.kind === "sym" && t.value === ";") {
        this.lx.next();
        continue;
      }
      if (t.kind === "ident") {
        switch (t.value) {
          case "message":
            this.lx.next();
            msg.messages.push(this.parseMessage());
            continue;
          case "enum":
            this.lx.next();
            msg.enums.push(this.parseEnum());
            continue;
          case "oneof":
            this.lx.next();
            msg.oneofs.push(this.parseOneof());
            continue;
          case "option": {
            this.lx.next();
            const { key, value } = this.parseOption();
            const f = featureFromOption(key, value);
            if (f)
              Object.assign(msg.features, f);
            this.expectSym(";");
            continue;
          }
          case "reserved":
            this.lx.next();
            this.skipToSemicolon();
            continue;
          case "map":
            msg.fields.push(this.parseMapField());
            continue;
          case "extensions":
            this.lx.next();
            this.skipToSemicolon();
            continue;
          case "extend":
            this.lx.next();
            this.skipBlock();
            continue;
        }
      }
      this.parseFieldOrGroup(msg);
    }
    return msg;
  }
  parseOneof() {
    const name = this.expectIdent();
    const oneof = { name, fields: [] };
    this.expectSym("{");
    for (;; ) {
      const t = this.lx.peek();
      if (t.kind === "sym" && t.value === "}") {
        this.lx.next();
        break;
      }
      if (t.kind === "sym" && t.value === ";") {
        this.lx.next();
        continue;
      }
      if (this.isKeyword(t, "option")) {
        this.lx.next();
        this.parseOption();
        this.expectSym(";");
        continue;
      }
      oneof.fields.push(this.parseField(true));
    }
    return oneof;
  }
  parseField(inOneof = false) {
    let label = "singular";
    const t = this.lx.peek();
    if (!inOneof && (t.value === "repeated" || t.value === "optional")) {
      label = t.value;
      this.lx.next();
    } else if (t.value === "repeated" || t.value === "optional") {
      this.err(`'${t.value}' is not allowed inside oneof`, t.line);
    }
    return this.parseFieldTail(label);
  }
  parseFieldTail(label) {
    const typeName = this.parseQualifiedName();
    const name = this.expectIdent();
    this.expectSym("=");
    const number = this.parseInt32();
    const field = { label, typeName, name, number, features: {} };
    this.parseFieldOptions(field);
    this.expectSym(";");
    return field;
  }
  parseFieldOrGroup(msg) {
    let label = "singular";
    const lead = this.lx.peek();
    if (lead.value === "repeated" || lead.value === "optional" || lead.value === "required") {
      label = lead.value;
      this.lx.next();
    }
    if (label === "required" && this.syntax !== "proto2") {
      this.err("'required' fields are only valid in proto2", lead.line);
    }
    if (this.isKeyword(this.lx.peek(), "group")) {
      if (this.syntax !== "proto2")
        this.err("groups are only valid in proto2", this.lx.peek().line);
      this.lx.next();
      const groupName = this.expectIdent();
      this.expectSym("=");
      const number = this.parseInt32();
      msg.messages.push(this.parseMessageBody(groupName));
      msg.fields.push({ label, typeName: groupName, name: groupName.toLowerCase(), number, features: { messageEncoding: "DELIMITED" } });
      return;
    }
    msg.fields.push(this.parseFieldTail(label));
  }
  parseMapField() {
    this.lx.next();
    this.expectSym("<");
    const key = this.parseQualifiedName();
    this.expectSym(",");
    const value = this.parseQualifiedName();
    this.expectSym(">");
    const name = this.expectIdent();
    this.expectSym("=");
    const number = this.parseInt32();
    const field = { label: "repeated", typeName: "", name, number, features: {}, map: { key, value } };
    this.parseFieldOptions(field);
    this.expectSym(";");
    return field;
  }
  parseFieldOptions(field) {
    if (!this.acceptSym("["))
      return;
    for (;; ) {
      const { key, value } = this.parseOption();
      if (key === "json_name")
        field.jsonName = value;
      else if (key === "packed")
        field.packedOption = value === "true";
      else {
        const f = featureFromOption(key, value);
        if (f)
          Object.assign(field.features, f);
      }
      if (this.acceptSym(","))
        continue;
      this.expectSym("]");
      break;
    }
  }
  parseOption() {
    let key;
    if (this.acceptSym("(")) {
      this.parseQualifiedName();
      this.expectSym(")");
      while (this.acceptSym("."))
        this.expectIdent();
      key = "";
    } else {
      key = this.expectIdent();
      while (this.acceptSym("."))
        key += "." + this.expectIdent();
    }
    this.expectSym("=");
    const value = this.parseOptionValue();
    return { key, value };
  }
  parseOptionValue() {
    const t = this.lx.next();
    if (t.kind === "str")
      return t.value;
    if (t.kind === "ident" || t.kind === "num")
      return t.value;
    if (t.kind === "sym" && (t.value === "-" || t.value === "+")) {
      const num = this.lx.next();
      if (num.kind !== "num")
        this.err(`bad option value '${t.value}${num.value}'`, t.line);
      return (t.value === "-" ? "-" : "") + num.value;
    }
    if (t.kind === "sym" && t.value === "{") {
      let depth = 1;
      while (depth > 0) {
        const n = this.lx.next();
        if (n.kind === "eof")
          this.err("unexpected EOF in option");
        if (n.kind === "sym" && n.value === "{")
          depth++;
        else if (n.kind === "sym" && n.value === "}")
          depth--;
      }
      return "";
    }
    this.err(`bad option value '${t.value}'`, t.line);
  }
  parseEnum() {
    const name = this.expectIdent();
    const en = { name, values: [], features: {} };
    this.expectSym("{");
    for (;; ) {
      const t = this.lx.peek();
      if (t.kind === "sym" && t.value === "}") {
        this.lx.next();
        break;
      }
      if (t.kind === "sym" && t.value === ";") {
        this.lx.next();
        continue;
      }
      if (this.isKeyword(t, "option")) {
        this.lx.next();
        const { key, value } = this.parseOption();
        const f = featureFromOption(key, value);
        if (f)
          Object.assign(en.features, f);
        this.expectSym(";");
        continue;
      }
      if (this.isKeyword(t, "reserved")) {
        this.lx.next();
        this.skipToSemicolon();
        continue;
      }
      const vname = this.expectIdent();
      this.expectSym("=");
      const num = this.parseInt32();
      if (this.acceptSym("[")) {
        for (;; ) {
          this.parseOption();
          if (this.acceptSym(","))
            continue;
          this.expectSym("]");
          break;
        }
      }
      this.expectSym(";");
      en.values.push({ name: vname, number: num });
    }
    return en;
  }
  expectStr() {
    const t = this.lx.next();
    if (t.kind !== "str")
      this.err(`expected string, got '${t.value}'`, t.line);
    return t.value;
  }
  parseInt32() {
    let sign = 1;
    const s = this.lx.peek();
    if (s.kind === "sym" && (s.value === "-" || s.value === "+")) {
      this.lx.next();
      sign = s.value === "-" ? -1 : 1;
    }
    const t = this.lx.next();
    if (t.kind !== "num")
      this.err(`expected number, got '${t.value}'`, t.line);
    const n = t.value.startsWith("0x") || t.value.startsWith("0X") ? parseInt(t.value, 16) : parseInt(t.value, 10);
    if (!Number.isFinite(n))
      this.err(`bad number '${t.value}'`, t.line);
    return sign * n;
  }
  parseQualifiedName() {
    let name = "";
    if (this.acceptSym("."))
      name = ".";
    name += this.expectIdent();
    while (this.lx.peek().kind === "sym" && this.lx.peek().value === ".") {
      this.lx.next();
      name += "." + this.expectIdent();
    }
    return name;
  }
  skipToSemicolon() {
    for (;; ) {
      const t = this.lx.next();
      if (t.kind === "eof")
        this.err("unexpected EOF");
      if (t.kind === "sym" && t.value === ";")
        return;
    }
  }
  skipBlock() {
    while (!(this.lx.peek().kind === "sym" && this.lx.peek().value === "{")) {
      if (this.lx.peek().kind === "eof")
        this.err("unexpected EOF");
      this.lx.next();
    }
    this.expectSym("{");
    let depth = 1;
    while (depth > 0) {
      const t = this.lx.next();
      if (t.kind === "eof")
        this.err("unexpected EOF in block");
      if (t.kind === "sym" && t.value === "{")
        depth++;
      else if (t.kind === "sym" && t.value === "}")
        depth--;
    }
  }
  static isScalar(name) {
    return SCALARS.has(name);
  }
}

// serialization/protobuf/link.ts
var PACKABLE_SCALARS = new Set([
  "double",
  "float",
  "int32",
  "int64",
  "uint32",
  "uint64",
  "sint32",
  "sint64",
  "fixed32",
  "fixed64",
  "sfixed32",
  "sfixed64",
  "bool"
]);
function camelCase(s) {
  let out = "";
  let up = false;
  for (const c of s) {
    if (c === "_")
      up = true;
    else {
      out += up ? c.toUpperCase() : c;
      up = false;
    }
  }
  return out;
}
function qualify(scope, name) {
  return scope ? scope + "." + name : name;
}
function link(files) {
  const messages = new Map;
  const enums = new Map;
  const jobs = [];
  function registerEnum(ast, scope, inherited) {
    const fullName = qualify(scope, ast.name);
    const closed = mergeFeatures(inherited, ast.features).enumType === "CLOSED";
    const byNumber = new Map;
    const byName = new Map;
    for (const v of ast.values) {
      if (!byNumber.has(v.number))
        byNumber.set(v.number, v.name);
      byName.set(v.name, v.number);
    }
    enums.set(fullName, { name: ast.name, fullName, values: ast.values, byNumber, byName, closed });
  }
  function registerMessage(ast, scope, inherited) {
    const fullName = qualify(scope, ast.name);
    const msgFeat = mergeFeatures(inherited, ast.features);
    const desc = {
      name: ast.name,
      fullName,
      fields: [],
      fieldByNumber: new Map,
      oneofs: [],
      isMapEntry: false
    };
    messages.set(fullName, desc);
    jobs.push({ ast, desc, scope: fullName, inherited: msgFeat });
    for (const e of ast.enums)
      registerEnum(e, fullName, msgFeat);
    for (const m of ast.messages)
      registerMessage(m, fullName, msgFeat);
  }
  for (const file of files) {
    const fileFeat = mergeFeatures(baseFeatures(file.syntax), file.features);
    for (const e of file.enums)
      registerEnum(e, file.package, fileFeat);
    for (const m of file.messages)
      registerMessage(m, file.package, fileFeat);
  }
  const registry = {
    messages,
    enums,
    get(n) {
      return messages.get(n) ?? enums.get(n);
    }
  };
  function resolveType(ref, scope) {
    if (Parser.isScalar(ref))
      return { kind: "scalar", scalar: ref };
    const abs = ref.startsWith(".");
    const bare = abs ? ref.slice(1) : ref;
    const tryNames = [];
    if (abs) {
      tryNames.push(bare);
    } else {
      const parts = scope ? scope.split(".") : [];
      for (let i = parts.length;i >= 0; i--) {
        tryNames.push([...parts.slice(0, i), bare].join("."));
      }
    }
    for (const n of tryNames) {
      const m = messages.get(n);
      if (m)
        return { kind: "message", message: m };
      const e = enums.get(n);
      if (e)
        return { kind: "enum", enum: e };
    }
    throw new Error(`protobuf: unknown type "${ref}" referenced from "${scope}"`);
  }
  function resolveField(ast, scope, inherited, oneofIndex) {
    const feat = mergeFeatures(inherited, ast.features);
    const jsonName = ast.jsonName ?? camelCase(ast.name);
    if (ast.map) {
      const keyType = resolveType(ast.map.key, scope);
      const valueType = resolveType(ast.map.value, scope);
      const key = { name: "key", jsonName: "key", number: 1, repeated: false, explicitPresence: false, packed: false, delimited: false, type: keyType, oneofIndex: -1 };
      const value = { name: "value", jsonName: "value", number: 2, repeated: false, explicitPresence: false, packed: false, delimited: false, type: valueType, oneofIndex: -1 };
      return { name: ast.name, jsonName, number: ast.number, repeated: false, explicitPresence: false, packed: false, delimited: false, type: valueType, oneofIndex: -1, map: { key, value } };
    }
    const type = resolveType(ast.typeName, scope);
    const repeated = ast.label === "repeated";
    let explicitPresence = false;
    let packed = false;
    if (repeated) {
      const packable = type.kind === "enum" || type.kind === "scalar" && PACKABLE_SCALARS.has(type.scalar);
      packed = packable && (ast.packedOption ?? feat.repeatedEncoding === "PACKED");
    } else if (type.kind === "message") {
      explicitPresence = true;
    } else if (ast.label === "optional" || oneofIndex >= 0) {
      explicitPresence = true;
    } else {
      explicitPresence = feat.fieldPresence === "EXPLICIT";
    }
    const delimited = type.kind === "message" && feat.messageEncoding === "DELIMITED";
    return { name: ast.name, jsonName, number: ast.number, repeated, explicitPresence, packed, delimited, type, oneofIndex };
  }
  for (const { ast, desc, scope, inherited } of jobs) {
    const add = (f) => {
      desc.fields.push(f);
      desc.fieldByNumber.set(f.number, f);
    };
    for (const af of ast.fields)
      add(resolveField(af, scope, inherited, -1));
    ast.oneofs.forEach((oneof, idx) => {
      const oneofIndex = desc.oneofs.length;
      const fieldNumbers = [];
      for (const af of oneof.fields) {
        const f = resolveField(af, scope, inherited, oneofIndex);
        add(f);
        fieldNumbers.push(f.number);
      }
      desc.oneofs.push({ name: oneof.name, fieldNumbers });
    });
  }
  return registry;
}

// serialization/protobuf/utf8.ts
function utf8Read(buf, start, end) {
  const len = end - start;
  if (len < 1)
    return "";
  let parts = null;
  const chunk = [];
  let i = 0;
  let t;
  let p = start;
  while (p < end) {
    t = buf[p++];
    if (t < 128) {
      chunk[i++] = t;
    } else if (t > 191 && t < 224) {
      chunk[i++] = (t & 31) << 6 | buf[p++] & 63;
    } else if (t > 239 && t < 365) {
      t = ((t & 7) << 18 | (buf[p++] & 63) << 12 | (buf[p++] & 63) << 6 | buf[p++] & 63) - 65536;
      chunk[i++] = 55296 + (t >> 10);
      chunk[i++] = 56320 + (t & 1023);
    } else {
      chunk[i++] = (t & 15) << 12 | (buf[p++] & 63) << 6 | buf[p++] & 63;
    }
    if (i > 8191) {
      (parts || (parts = [])).push(String.fromCharCode.apply(String, chunk));
      i = 0;
    }
  }
  if (parts) {
    if (i)
      parts.push(String.fromCharCode.apply(String, chunk.slice(0, i)));
    return parts.join("");
  }
  return String.fromCharCode.apply(String, chunk.slice(0, i));
}
function utf8Length(str) {
  let len = 0;
  for (let i = 0;i < str.length; i++) {
    const c = str.charCodeAt(i);
    if (c < 128)
      len += 1;
    else if (c < 2048)
      len += 2;
    else if (c >= 55296 && c <= 56319 && i + 1 < str.length && (str.charCodeAt(i + 1) & 64512) === 56320) {
      i++;
      len += 4;
    } else
      len += 3;
  }
  return len;
}
function utf8Write(str, buf, offset) {
  let p = offset;
  for (let i = 0;i < str.length; i++) {
    let c = str.charCodeAt(i);
    if (c < 128) {
      buf[p++] = c;
    } else if (c < 2048) {
      buf[p++] = c >> 6 | 192;
      buf[p++] = c & 63 | 128;
    } else if (c >= 55296 && c <= 56319 && i + 1 < str.length && (str.charCodeAt(i + 1) & 64512) === 56320) {
      c = 65536 + ((c & 1023) << 10) + (str.charCodeAt(++i) & 1023);
      buf[p++] = c >> 18 | 240;
      buf[p++] = c >> 12 & 63 | 128;
      buf[p++] = c >> 6 & 63 | 128;
      buf[p++] = c & 63 | 128;
    } else {
      buf[p++] = c >> 12 | 224;
      buf[p++] = c >> 6 & 63 | 128;
      buf[p++] = c & 63 | 128;
    }
  }
  return p;
}

// serialization/protobuf/reader.ts
var WIRE_VARINT = 0;
var WIRE_I64 = 1;
var WIRE_LEN = 2;
var WIRE_SGROUP = 3;
var WIRE_EGROUP = 4;
var WIRE_I32 = 5;

class Reader {
  buf;
  pos;
  end;
  view;
  constructor(buf, start = 0, end = buf.length) {
    this.buf = buf;
    this.pos = start;
    this.end = end;
    this.view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  }
  eof() {
    return this.pos >= this.end;
  }
  need(n) {
    if (this.pos + n > this.end)
      throw new Error("protobuf: unexpected end of input");
  }
  uint32() {
    let result = 0;
    let shift = 0;
    let count = 0;
    let b;
    do {
      if (this.pos >= this.end)
        throw new Error("protobuf: unexpected end of input (varint)");
      if (++count > 10)
        throw new Error("protobuf: varint is too long");
      b = this.buf[this.pos++];
      if (shift < 32)
        result = (result | (b & 127) << shift) >>> 0;
      shift += 7;
    } while (b & 128);
    return result >>> 0;
  }
  int32() {
    return this.uint32() | 0;
  }
  sint32() {
    const n = this.uint32();
    return n >>> 1 ^ -(n & 1);
  }
  varint64() {
    let result = 0n;
    let shift = 0n;
    let count = 0;
    let b;
    do {
      if (this.pos >= this.end)
        throw new Error("protobuf: unexpected end of input (varint)");
      if (++count > 10)
        throw new Error("protobuf: varint is too long");
      b = this.buf[this.pos++];
      result |= BigInt(b & 127) << shift;
      shift += 7n;
    } while (b & 128);
    return BigInt.asUintN(64, result);
  }
  int64() {
    return BigInt.asIntN(64, this.varint64());
  }
  uint64() {
    return this.varint64();
  }
  sint64() {
    const u = this.varint64();
    return BigInt.asIntN(64, u >> 1n ^ -(u & 1n));
  }
  bool() {
    return this.varint64() !== 0n;
  }
  fixed32() {
    this.need(4);
    const v = this.view.getUint32(this.pos, true);
    this.pos += 4;
    return v;
  }
  sfixed32() {
    this.need(4);
    const v = this.view.getInt32(this.pos, true);
    this.pos += 4;
    return v;
  }
  float() {
    this.need(4);
    const v = this.view.getFloat32(this.pos, true);
    this.pos += 4;
    return v;
  }
  fixed64() {
    this.need(8);
    const v = this.view.getBigUint64(this.pos, true);
    this.pos += 8;
    return v;
  }
  sfixed64() {
    this.need(8);
    const v = this.view.getBigInt64(this.pos, true);
    this.pos += 8;
    return v;
  }
  double() {
    this.need(8);
    const v = this.view.getFloat64(this.pos, true);
    this.pos += 8;
    return v;
  }
  string() {
    const len = this.uint32();
    this.need(len);
    const start = this.pos;
    this.pos += len;
    return utf8Read(this.buf, start, start + len);
  }
  bytes() {
    const len = this.uint32();
    this.need(len);
    const start = this.pos;
    this.pos += len;
    return this.buf.slice(start, start + len);
  }
  fork() {
    const len = this.uint32();
    this.need(len);
    const start = this.pos;
    this.pos += len;
    return new Reader(this.buf, start, start + len);
  }
  skip(wireType, depth = 0) {
    switch (wireType) {
      case WIRE_VARINT: {
        let b;
        do {
          if (this.pos >= this.end)
            throw new Error("protobuf: unexpected end of input (varint)");
          b = this.buf[this.pos++];
        } while (b & 128);
        break;
      }
      case WIRE_I64:
        this.need(8);
        this.pos += 8;
        break;
      case WIRE_LEN: {
        const len = this.uint32();
        this.need(len);
        this.pos += len;
        break;
      }
      case WIRE_I32:
        this.need(4);
        this.pos += 4;
        break;
      case WIRE_SGROUP: {
        if (depth > 100)
          throw new Error("protobuf: group nesting exceeds maximum depth");
        for (;; ) {
          const tag = this.uint32();
          const wt = tag & 7;
          if (wt === WIRE_EGROUP)
            break;
          this.skip(wt, depth + 1);
        }
        break;
      }
      case WIRE_EGROUP:
        break;
      default:
        throw new Error(`protobuf: cannot skip wire type ${wireType}`);
    }
  }
  rawFrom(tagStart) {
    return this.buf.slice(tagStart, this.pos);
  }
}

// serialization/protobuf/decode.ts
var UNKNOWN = Symbol.for("esrun.protobuf.unknown");
var MAX_DEPTH = 100;
function pushUnknown(out, bytes) {
  (out[UNKNOWN] ?? (out[UNKNOWN] = [])).push(bytes);
}
function unknownEnumEntry(fieldNo, valueBytes) {
  const tag = [];
  let v = fieldNo * 8;
  while (v > 127) {
    tag.push(v & 127 | 128);
    v = Math.floor(v / 128);
  }
  tag.push(v);
  const out = new Uint8Array(tag.length + valueBytes.length);
  out.set(tag, 0);
  out.set(valueBytes, tag.length);
  return out;
}
function expectedWire(type) {
  if (type.kind === "message")
    return 2;
  if (type.kind === "enum")
    return 0;
  switch (type.scalar) {
    case "string":
    case "bytes":
      return 2;
    case "double":
    case "fixed64":
    case "sfixed64":
      return 1;
    case "float":
    case "fixed32":
    case "sfixed32":
      return 5;
    default:
      return 0;
  }
}
function readScalar(r, t) {
  switch (t) {
    case "double":
      return r.double();
    case "float":
      return r.float();
    case "int32":
      return r.int32();
    case "int64":
      return r.int64();
    case "uint32":
      return r.uint32();
    case "uint64":
      return r.uint64();
    case "sint32":
      return r.sint32();
    case "sint64":
      return r.sint64();
    case "fixed32":
      return r.fixed32();
    case "fixed64":
      return r.fixed64();
    case "sfixed32":
      return r.sfixed32();
    case "sfixed64":
      return r.sfixed64();
    case "bool":
      return r.bool();
    case "string":
      return r.string();
    case "bytes":
      return r.bytes();
  }
}
function readEnum(r, e) {
  const n = r.int32();
  return e.byNumber.get(n) ?? n;
}
function readSingle(r, type, depth) {
  if (type.kind === "scalar")
    return readScalar(r, type.scalar);
  if (type.kind === "enum")
    return readEnum(r, type.enum);
  return decode(type.message, r.fork(), undefined, undefined, depth + 1);
}
function clearOneof(message, out, field) {
  for (const num of message.oneofs[field.oneofIndex].fieldNumbers) {
    const other = message.fieldByNumber.get(num);
    if (other.jsonName !== field.jsonName)
      delete out[other.jsonName];
  }
}
function decode(message, r, target, groupFieldNo, depth = 0) {
  if (depth > MAX_DEPTH)
    throw new Error("protobuf: message nesting exceeds maximum depth");
  const out = target ?? {};
  for (;; ) {
    if (r.eof()) {
      if (groupFieldNo !== undefined)
        throw new Error("protobuf: unexpected end of input inside group");
      break;
    }
    const tagStart = r.pos;
    const tag = r.uint32();
    const fieldNo = tag >>> 3;
    const wire = tag & 7;
    if (wire === WIRE_EGROUP) {
      if (groupFieldNo !== undefined && fieldNo === groupFieldNo)
        break;
      throw new Error("protobuf: unexpected end-group");
    }
    if (fieldNo === 0)
      throw new Error("protobuf: invalid field number 0");
    const field = message.fieldByNumber.get(fieldNo);
    if (!field) {
      r.skip(wire);
      pushUnknown(out, r.buf.slice(tagStart, r.pos));
      continue;
    }
    if (field.delimited && field.type.kind === "message" && wire === WIRE_SGROUP) {
      if (field.repeated) {
        const arr = out[field.jsonName] ?? (out[field.jsonName] = []);
        arr.push(decode(field.type.message, r, undefined, fieldNo, depth + 1));
      } else {
        if (field.oneofIndex >= 0)
          clearOneof(message, out, field);
        const existing = out[field.jsonName];
        const into = existing && typeof existing === "object" ? existing : undefined;
        out[field.jsonName] = decode(field.type.message, r, into, fieldNo, depth + 1);
      }
      continue;
    }
    if (field.map) {
      const sub = r.fork();
      let k = defaultForType(field.map.key.type);
      let v = defaultForType(field.map.value.type);
      while (!sub.eof()) {
        const t = sub.uint32();
        const n = t >>> 3;
        const w = t & 7;
        if (n === 1)
          k = readSingle(sub, field.map.key.type, depth);
        else if (n === 2)
          v = readSingle(sub, field.map.value.type, depth);
        else
          sub.skip(w);
      }
      const obj = out[field.jsonName] ?? (out[field.jsonName] = {});
      obj[String(k)] = v;
      continue;
    }
    if (field.repeated) {
      const arr = out[field.jsonName] ?? (out[field.jsonName] = []);
      const enumType = field.type.kind === "enum" ? field.type.enum : null;
      const packable = enumType !== null || field.type.kind === "scalar" && field.type.scalar !== "string" && field.type.scalar !== "bytes";
      if (wire === WIRE_LEN && packable) {
        const sub = r.fork();
        while (!sub.eof()) {
          if (enumType) {
            const elemStart = sub.pos;
            const n = sub.int32();
            const name = enumType.byNumber.get(n);
            if (name !== undefined)
              arr.push(name);
            else if (enumType.closed)
              pushUnknown(out, unknownEnumEntry(field.number, sub.buf.slice(elemStart, sub.pos)));
            else
              arr.push(n);
          } else {
            arr.push(readScalar(sub, field.type.scalar));
          }
        }
      } else if (enumType) {
        const n = r.int32();
        const name = enumType.byNumber.get(n);
        if (name !== undefined)
          arr.push(name);
        else if (enumType.closed)
          pushUnknown(out, r.buf.slice(tagStart, r.pos));
        else
          arr.push(n);
      } else {
        arr.push(readSingle(r, field.type, depth));
      }
      continue;
    }
    if (wire !== expectedWire(field.type) && !(wire === WIRE_LEN && field.type.kind === "message")) {
      r.skip(wire);
      pushUnknown(out, r.buf.slice(tagStart, r.pos));
      continue;
    }
    if (field.type.kind === "enum" && field.type.enum.closed) {
      const name = field.type.enum.byNumber.get(r.int32());
      if (name === undefined) {
        pushUnknown(out, r.buf.slice(tagStart, r.pos));
        continue;
      }
      if (field.oneofIndex >= 0)
        clearOneof(message, out, field);
      out[field.jsonName] = name;
      continue;
    }
    if (field.oneofIndex >= 0)
      clearOneof(message, out, field);
    if (field.type.kind === "message") {
      const existing = out[field.jsonName];
      const into = existing && typeof existing === "object" ? existing : undefined;
      out[field.jsonName] = decode(field.type.message, r.fork(), into, undefined, depth + 1);
    } else {
      out[field.jsonName] = readSingle(r, field.type, depth);
    }
  }
  return out;
}
function defaultForType(type) {
  if (type.kind === "scalar") {
    switch (type.scalar) {
      case "int64":
      case "uint64":
      case "sint64":
      case "fixed64":
      case "sfixed64":
        return 0n;
      case "bool":
        return false;
      case "string":
        return "";
      case "bytes":
        return new Uint8Array(0);
      default:
        return 0;
    }
  }
  if (type.kind === "enum")
    return type.enum.byNumber.get(0) ?? 0;
  return {};
}

// serialization/protobuf/writer.ts
class Writer {
  buf;
  len;
  view;
  constructor(capacity = 64) {
    this.buf = new Uint8Array(capacity);
    this.len = 0;
    this.view = new DataView(this.buf.buffer);
  }
  ensure(n) {
    const need = this.len + n;
    if (need <= this.buf.length)
      return;
    let cap = this.buf.length * 2;
    while (cap < need)
      cap *= 2;
    const next = new Uint8Array(cap);
    next.set(this.buf.subarray(0, this.len));
    this.buf = next;
    this.view = new DataView(this.buf.buffer);
  }
  finish() {
    return this.buf.slice(0, this.len);
  }
  get length() {
    return this.len;
  }
  uint32(value) {
    value = value >>> 0;
    this.ensure(5);
    while (value > 127) {
      this.buf[this.len++] = value & 127 | 128;
      value >>>= 7;
    }
    this.buf[this.len++] = value;
  }
  int32(value) {
    if (value < 0)
      this.varint64(BigInt.asUintN(64, BigInt(value)));
    else
      this.uint32(value);
  }
  sint32(value) {
    this.uint32((value << 1 ^ value >> 31) >>> 0);
  }
  varint64(value) {
    value = BigInt.asUintN(64, value);
    this.ensure(10);
    while (value > 0x7fn) {
      this.buf[this.len++] = Number(value & 0x7fn) | 128;
      value >>= 7n;
    }
    this.buf[this.len++] = Number(value);
  }
  sint64(value) {
    const v = BigInt.asIntN(64, value);
    this.varint64(v << 1n ^ v >> 63n);
  }
  bool(value) {
    this.ensure(1);
    this.buf[this.len++] = value ? 1 : 0;
  }
  tag(fieldNo, wireType) {
    this.uint32((fieldNo << 3 | wireType) >>> 0);
  }
  fixed32(value) {
    this.ensure(4);
    this.view.setUint32(this.len, value >>> 0, true);
    this.len += 4;
  }
  sfixed32(value) {
    this.ensure(4);
    this.view.setInt32(this.len, value | 0, true);
    this.len += 4;
  }
  float(value) {
    this.ensure(4);
    this.view.setFloat32(this.len, value, true);
    this.len += 4;
  }
  fixed64(value) {
    this.ensure(8);
    this.view.setBigUint64(this.len, BigInt.asUintN(64, value), true);
    this.len += 8;
  }
  sfixed64(value) {
    this.ensure(8);
    this.view.setBigInt64(this.len, BigInt.asIntN(64, value), true);
    this.len += 8;
  }
  double(value) {
    this.ensure(8);
    this.view.setFloat64(this.len, value, true);
    this.len += 8;
  }
  string(value) {
    const n = utf8Length(value);
    this.uint32(n);
    this.ensure(n);
    this.len = utf8Write(value, this.buf, this.len);
  }
  bytes(value) {
    this.uint32(value.length);
    this.ensure(value.length);
    this.buf.set(value, this.len);
    this.len += value.length;
  }
  raw(value) {
    this.ensure(value.length);
    this.buf.set(value, this.len);
    this.len += value.length;
  }
  lenDelimited(fieldNo, child) {
    this.tag(fieldNo, WIRE_LEN);
    const bytes = child.finish();
    this.uint32(bytes.length);
    this.raw(bytes);
  }
}

// serialization/protobuf/encode.ts
function writeScalarRaw(w, t, v) {
  switch (t) {
    case "double":
      w.double(v);
      break;
    case "float":
      w.float(v);
      break;
    case "int32":
      w.int32(v);
      break;
    case "int64":
      w.varint64(BigInt(v));
      break;
    case "uint32":
      w.uint32(v);
      break;
    case "uint64":
      w.varint64(BigInt(v));
      break;
    case "sint32":
      w.sint32(v);
      break;
    case "sint64":
      w.sint64(BigInt(v));
      break;
    case "fixed32":
      w.fixed32(v);
      break;
    case "fixed64":
      w.fixed64(BigInt(v));
      break;
    case "sfixed32":
      w.sfixed32(v);
      break;
    case "sfixed64":
      w.sfixed64(BigInt(v));
      break;
    case "bool":
      w.bool(v);
      break;
    case "string":
      w.string(v);
      break;
    case "bytes":
      w.bytes(v);
      break;
  }
}
function enumNumber(e, v) {
  if (typeof v === "number")
    return v;
  const n = e.byName.get(v);
  if (n === undefined)
    throw new Error(`protobuf: unknown enum value "${String(v)}" for ${e.fullName}`);
  return n;
}
function wireFor(type) {
  if (type.kind === "message")
    return 2;
  if (type.kind === "enum")
    return 0;
  switch (type.scalar) {
    case "string":
    case "bytes":
      return 2;
    case "double":
    case "fixed64":
    case "sfixed64":
      return 1;
    case "float":
    case "fixed32":
    case "sfixed32":
      return 5;
    default:
      return 0;
  }
}
function writeField(w, field, v) {
  const type = field.type;
  if (type.kind === "message") {
    if (field.delimited) {
      w.tag(field.number, WIRE_SGROUP);
      encode(type.message, v, w);
      w.tag(field.number, WIRE_EGROUP);
      return;
    }
    const child = new Writer;
    encode(type.message, v, child);
    w.lenDelimited(field.number, child);
    return;
  }
  if (type.kind === "enum") {
    w.tag(field.number, 0);
    w.int32(enumNumber(type.enum, v));
    return;
  }
  w.tag(field.number, wireFor(type));
  writeScalarRaw(w, type.scalar, v);
}
function isDefault(type, v) {
  if (type.kind === "scalar") {
    switch (type.scalar) {
      case "int64":
      case "uint64":
      case "sint64":
      case "fixed64":
      case "sfixed64":
        return BigInt(v) === 0n;
      case "bool":
        return v === false;
      case "string":
        return v === "";
      case "bytes":
        return v.length === 0;
      default:
        return v === 0;
    }
  }
  if (type.kind === "enum") {
    const n = enumNumber(type.enum, v);
    return n === 0;
  }
  return false;
}
function mapKeyTyped(t, k) {
  switch (t) {
    case "string":
      return k;
    case "bool":
      return k === "true";
    case "int64":
    case "uint64":
    case "sint64":
    case "fixed64":
    case "sfixed64":
      return BigInt(k);
    default:
      return Number(k);
  }
}
function encode(message, value, w) {
  for (const field of message.fields) {
    const v = value[field.jsonName];
    if (field.map) {
      if (v == null)
        continue;
      const keyType = field.map.key.type;
      for (const [k, val] of Object.entries(v)) {
        const entry = new Writer;
        writeField(entry, field.map.key, mapKeyTyped(keyType.scalar, k));
        writeField(entry, field.map.value, val);
        w.lenDelimited(field.number, entry);
      }
      continue;
    }
    if (field.repeated) {
      if (!Array.isArray(v) || v.length === 0)
        continue;
      if (field.packed) {
        const child = new Writer;
        if (field.type.kind === "enum") {
          for (const e of v)
            child.int32(enumNumber(field.type.enum, e));
        } else {
          const scalar = field.type.scalar;
          for (const e of v)
            writeScalarRaw(child, scalar, e);
        }
        w.tag(field.number, WIRE_LEN);
        w.uint32(child.length);
        w.raw(child.finish());
      } else {
        for (const e of v)
          writeField(w, field, e);
      }
      continue;
    }
    if (v === undefined || v === null)
      continue;
    if (!field.explicitPresence && isDefault(field.type, v))
      continue;
    writeField(w, field, v);
  }
  const unknown = value[UNKNOWN];
  if (unknown)
    for (const raw of unknown)
      w.raw(raw);
}

// serialization/protobuf/descriptor.ts
var BIGINT_SCALARS = new Set([
  "int64",
  "uint64",
  "sint64",
  "fixed64",
  "sfixed64"
]);
function scalarDefault(t) {
  switch (t) {
    case "double":
    case "float":
    case "int32":
    case "uint32":
    case "sint32":
    case "fixed32":
    case "sfixed32":
      return 0;
    case "int64":
    case "uint64":
    case "sint64":
    case "fixed64":
    case "sfixed64":
      return 0n;
    case "bool":
      return false;
    case "string":
      return "";
    case "bytes":
      return new Uint8Array(0);
  }
}

// serialization/protobuf/json.ts
var DROP = Symbol("drop");
var WRAPPERS = new Set([
  "google.protobuf.DoubleValue",
  "google.protobuf.FloatValue",
  "google.protobuf.Int64Value",
  "google.protobuf.UInt64Value",
  "google.protobuf.Int32Value",
  "google.protobuf.UInt32Value",
  "google.protobuf.BoolValue",
  "google.protobuf.StringValue",
  "google.protobuf.BytesValue"
]);
var SPECIAL_JSON_WKT = new Set([
  "google.protobuf.Timestamp",
  "google.protobuf.Duration",
  "google.protobuf.FieldMask",
  "google.protobuf.Value",
  "google.protobuf.ListValue",
  "google.protobuf.Struct",
  "google.protobuf.Any",
  ...WRAPPERS
]);
var I32_MIN = -2147483648;
var I32_MAX = 2147483647;
var U32_MAX = 4294967295;
var I64_MIN = -9223372036854775808n;
var I64_MAX = 9223372036854775807n;
var U64_MAX = 18446744073709551615n;
var TS_MIN = -62135596800n;
var TS_MAX = 253402300799n;
var DUR_MAX = 315576000000n;
var NUM_RE = /^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?$/;
var B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
var B64INV = /* @__PURE__ */ (() => {
  const t = new Int16Array(256).fill(-1);
  for (let i = 0;i < B64.length; i++)
    t[B64.charCodeAt(i)] = i;
  return t;
})();
function base64Encode(bytes) {
  let out = "";
  let i = 0;
  for (;i + 2 < bytes.length; i += 3) {
    const n = bytes[i] << 16 | bytes[i + 1] << 8 | bytes[i + 2];
    out += B64[n >> 18 & 63] + B64[n >> 12 & 63] + B64[n >> 6 & 63] + B64[n & 63];
  }
  const rem = bytes.length - i;
  if (rem === 1) {
    const n = bytes[i] << 16;
    out += B64[n >> 18 & 63] + B64[n >> 12 & 63] + "==";
  } else if (rem === 2) {
    const n = bytes[i] << 16 | bytes[i + 1] << 8;
    out += B64[n >> 18 & 63] + B64[n >> 12 & 63] + B64[n >> 6 & 63] + "=";
  }
  return out;
}
function base64Decode(s) {
  const out = [];
  let bits = 0;
  let nbits = 0;
  for (let i = 0;i < s.length; i++) {
    const ch = s.charCodeAt(i);
    if (ch === 61)
      break;
    if (ch === 32 || ch === 10 || ch === 13 || ch === 9)
      continue;
    const v = ch === 45 ? 62 : ch === 95 ? 63 : B64INV[ch];
    if (v < 0)
      throw new Error("protobuf: invalid base64 in JSON");
    bits = bits << 6 | v;
    nbits += 6;
    if (nbits >= 8) {
      nbits -= 8;
      out.push(bits >> nbits & 255);
    }
  }
  return new Uint8Array(out);
}
function camelCase2(s) {
  let out = "";
  let up = false;
  for (const c of s) {
    if (c === "_")
      up = true;
    else {
      out += up ? c.toUpperCase() : c;
      up = false;
    }
  }
  return out;
}
function snakeCase(s) {
  return s.replace(/[A-Z]/g, (c) => "_" + c.toLowerCase());
}
function parseIntStrict(j, min, max) {
  let n;
  if (typeof j === "number")
    n = j;
  else if (typeof j === "string") {
    if (!NUM_RE.test(j))
      throw new Error(`protobuf: invalid integer ${JSON.stringify(j)}`);
    n = Number(j);
  } else
    throw new Error("protobuf: integer field expects a number or string");
  if (!Number.isInteger(n))
    throw new Error(`protobuf: ${n} is not an integer`);
  if (n < min || n > max)
    throw new Error(`protobuf: integer ${n} out of range`);
  return n;
}
function parseBigIntStrict(j, min, max) {
  let b;
  if (typeof j === "number") {
    if (!Number.isInteger(j))
      throw new Error(`protobuf: ${j} is not an integer`);
    b = BigInt(j);
  } else if (typeof j === "string") {
    if (/^-?(?:0|[1-9][0-9]*)$/.test(j))
      b = BigInt(j);
    else {
      if (!NUM_RE.test(j))
        throw new Error(`protobuf: invalid integer ${JSON.stringify(j)}`);
      const n = Number(j);
      if (!Number.isInteger(n))
        throw new Error(`protobuf: ${j} is not an integer`);
      b = BigInt(n);
    }
  } else
    throw new Error("protobuf: integer field expects a number or string");
  if (b < min || b > max)
    throw new Error(`protobuf: integer ${b} out of range`);
  return b;
}
var FLOAT_MAX = 340282346638528860000000000000000000000;
function parseFloatStrict(j, isFloat) {
  let n;
  if (typeof j === "number")
    n = j;
  else if (typeof j === "string") {
    if (j === "NaN")
      return NaN;
    if (j === "Infinity")
      return Infinity;
    if (j === "-Infinity")
      return -Infinity;
    if (!NUM_RE.test(j))
      throw new Error(`protobuf: invalid number ${JSON.stringify(j)}`);
    n = Number(j);
  } else
    throw new Error("protobuf: float field expects a number or string");
  if (!Number.isFinite(n))
    throw new Error("protobuf: number out of range");
  if (isFloat && Math.abs(n) > FLOAT_MAX)
    throw new Error("protobuf: float out of range");
  return n;
}
function validateUtf16(s) {
  for (let i = 0;i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c >= 55296 && c <= 56319) {
      const next = s.charCodeAt(i + 1);
      if (!(next >= 56320 && next <= 57343))
        throw new Error("protobuf: unpaired UTF-16 surrogate in string");
      i++;
    } else if (c >= 56320 && c <= 57343) {
      throw new Error("protobuf: unpaired UTF-16 surrogate in string");
    }
  }
}
function nanosFraction(nanos) {
  const s = String(nanos).padStart(9, "0");
  if (s.endsWith("000000"))
    return s.slice(0, 3);
  if (s.endsWith("000"))
    return s.slice(0, 6);
  return s;
}
function timestampToJson(value) {
  const seconds = BigInt(value.seconds ?? 0);
  const nanos = Number(value.nanos ?? 0);
  if (seconds < TS_MIN || seconds > TS_MAX)
    throw new Error("protobuf: Timestamp seconds out of range");
  if (nanos < 0 || nanos > 999999999)
    throw new Error("protobuf: Timestamp nanos out of range");
  const date = new Date(Number(seconds) * 1000);
  const base = date.toISOString().slice(0, 19);
  return base + (nanos ? "." + nanosFraction(nanos) : "") + "Z";
}
function timestampFromJson(j) {
  if (typeof j !== "string")
    throw new Error("protobuf: Timestamp JSON must be a string");
  const m = /^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(\d+))?(Z|[+-]\d{2}:\d{2})$/.exec(j);
  if (!m)
    throw new Error(`protobuf: invalid Timestamp "${j}"`);
  const ms = Date.parse(m[1] + (m[3] === "Z" ? "Z" : m[3]));
  if (Number.isNaN(ms))
    throw new Error(`protobuf: invalid Timestamp "${j}"`);
  const seconds = BigInt(Math.floor(ms / 1000));
  const nanos = m[2] ? Number(m[2].padEnd(9, "0").slice(0, 9)) : 0;
  if (seconds < TS_MIN || seconds > TS_MAX)
    throw new Error(`protobuf: Timestamp "${j}" out of range`);
  const out = {};
  if (seconds !== 0n)
    out.seconds = seconds;
  if (nanos !== 0)
    out.nanos = nanos;
  return out;
}
function durationToJson(value) {
  const seconds = BigInt(value.seconds ?? 0);
  const nanos = Number(value.nanos ?? 0);
  if (seconds < -DUR_MAX || seconds > DUR_MAX)
    throw new Error("protobuf: Duration seconds out of range");
  if (nanos < -999999999 || nanos > 999999999)
    throw new Error("protobuf: Duration nanos out of range");
  if (seconds !== 0n && nanos !== 0 && seconds < 0n !== nanos < 0) {
    throw new Error("protobuf: Duration seconds and nanos must share sign");
  }
  const neg = seconds < 0n || nanos < 0;
  const absSec = seconds < 0n ? -seconds : seconds;
  const absNanos = Math.abs(nanos);
  return (neg ? "-" : "") + absSec.toString() + (absNanos ? "." + nanosFraction(absNanos) : "") + "s";
}
function durationFromJson(j) {
  if (typeof j !== "string")
    throw new Error("protobuf: Duration JSON must be a string");
  const m = /^(-)?(\d+)(?:\.(\d+))?s$/.exec(j);
  if (!m)
    throw new Error(`protobuf: invalid Duration "${j}"`);
  let seconds = BigInt(m[2]);
  let nanos = m[3] ? Number(m[3].padEnd(9, "0").slice(0, 9)) : 0;
  if (m[1] === "-") {
    seconds = -seconds;
    nanos = -nanos;
  }
  if (seconds < -DUR_MAX || seconds > DUR_MAX)
    throw new Error(`protobuf: Duration "${j}" out of range`);
  const out = {};
  if (seconds !== 0n)
    out.seconds = seconds;
  if (nanos !== 0)
    out.nanos = nanos;
  return out;
}
function valueToJson(value, registry) {
  if ("nullValue" in value)
    return null;
  if ("numberValue" in value) {
    const n = value.numberValue;
    if (!Number.isFinite(n))
      throw new Error("protobuf: Value number_value must be finite");
    return n;
  }
  if ("stringValue" in value)
    return value.stringValue;
  if ("boolValue" in value)
    return value.boolValue;
  if ("structValue" in value)
    return structToJson(value.structValue, registry);
  if ("listValue" in value)
    return listValueToJson(value.listValue, registry);
  return null;
}
function valueFromJson(j, ctx) {
  if (j === null)
    return { nullValue: "NULL_VALUE" };
  switch (typeof j) {
    case "number":
      if (!Number.isFinite(j))
        throw new Error("protobuf: Value number must be finite");
      return { numberValue: j };
    case "string":
      return { stringValue: j };
    case "boolean":
      return { boolValue: j };
  }
  if (Array.isArray(j))
    return { listValue: { values: j.map((e) => valueFromJson(e, ctx)) } };
  return { structValue: structFromJson(j, ctx) };
}
function structToJson(value, registry) {
  const out = {};
  const fields = value.fields;
  if (fields)
    for (const [k, v] of Object.entries(fields))
      out[k] = valueToJson(v, registry);
  return out;
}
function structFromJson(j, ctx) {
  const fields = {};
  for (const [k, v] of Object.entries(j))
    fields[k] = valueFromJson(v, ctx);
  return { fields };
}
function listValueToJson(value, registry) {
  const vals = value.values ?? [];
  return vals.map((v) => valueToJson(v, registry));
}
function listValueFromJson(j, ctx) {
  if (!Array.isArray(j))
    throw new Error("protobuf: ListValue JSON must be an array");
  return { values: j.map((e) => valueFromJson(e, ctx)) };
}
function fieldMaskToJson(value) {
  const paths = value.paths ?? [];
  return paths.map((p) => {
    const camel = p.split(".").map(camelCase2).join(".");
    if (camel.split(".").map(snakeCase).join(".") !== p) {
      throw new Error(`protobuf: FieldMask path "${p}" is not a valid field path`);
    }
    return camel;
  }).join(",");
}
function fieldMaskFromJson(j) {
  if (typeof j !== "string")
    throw new Error("protobuf: FieldMask JSON must be a string");
  if (j === "")
    return {};
  return {
    paths: j.split(",").map((p) => {
      const snake = p.split(".").map(snakeCase).join(".");
      if (snake.split(".").map(camelCase2).join(".") !== p) {
        throw new Error(`protobuf: invalid FieldMask path "${p}"`);
      }
      return snake;
    })
  };
}
function wrapperToJson(message, value) {
  const field = message.fields[0];
  const scalar = field.type.scalar;
  const v = value[field.jsonName];
  return scalarToJson(scalar, v === undefined ? scalarDefault(scalar) : v);
}
function wrapperFromJson(message, j) {
  const field = message.fields[0];
  const scalar = field.type.scalar;
  return { [field.jsonName]: scalarFromJson(scalar, j) };
}
function typeName(typeUrl) {
  return typeUrl.slice(typeUrl.lastIndexOf("/") + 1);
}
function anyToJson(value, registry) {
  const typeUrl = value.typeUrl;
  if (!typeUrl)
    return {};
  const name = typeName(typeUrl);
  const m = registry.messages.get(name);
  if (!m)
    throw new Error(`protobuf: Any references unknown type "${typeUrl}"`);
  const bytes = value.value ?? new Uint8Array(0);
  const inner = messageToJson(m, decode(m, new Reader(bytes)), registry);
  if (SPECIAL_JSON_WKT.has(name))
    return { "@type": typeUrl, value: inner };
  return { "@type": typeUrl, ...inner };
}
function anyFromJson(j, ctx) {
  if (j === null || typeof j !== "object" || Array.isArray(j)) {
    throw new Error("protobuf: Any JSON must be an object");
  }
  const typeUrl = j["@type"];
  if (!typeUrl)
    return {};
  const name = typeName(typeUrl);
  const m = ctx.registry.messages.get(name);
  if (!m)
    throw new Error(`protobuf: Any references unknown type "${typeUrl}"`);
  let innerValue;
  if (SPECIAL_JSON_WKT.has(name)) {
    innerValue = messageFromJsonCtx(m, j.value ?? null, ctx);
  } else {
    const { "@type": _omit, ...rest } = j;
    innerValue = messageFromJsonCtx(m, rest, ctx);
  }
  const w = new Writer;
  encode(m, innerValue, w);
  return { typeUrl, value: w.finish() };
}
function scalarToJson(t, v) {
  if (BIGINT_SCALARS.has(t))
    return String(v);
  switch (t) {
    case "double":
    case "float": {
      const n = v;
      if (Number.isFinite(n))
        return n;
      if (Number.isNaN(n))
        return "NaN";
      return n > 0 ? "Infinity" : "-Infinity";
    }
    case "bytes":
      return base64Encode(v);
    default:
      return v;
  }
}
function scalarFromJson(t, j) {
  switch (t) {
    case "int32":
    case "sint32":
    case "sfixed32":
      return parseIntStrict(j, I32_MIN, I32_MAX);
    case "uint32":
    case "fixed32":
      return parseIntStrict(j, 0, U32_MAX);
    case "int64":
    case "sint64":
    case "sfixed64":
      return parseBigIntStrict(j, I64_MIN, I64_MAX);
    case "uint64":
    case "fixed64":
      return parseBigIntStrict(j, 0n, U64_MAX);
    case "double":
      return parseFloatStrict(j, false);
    case "float":
      return parseFloatStrict(j, true);
    case "bool":
      if (typeof j !== "boolean")
        throw new Error("protobuf: bool field expects true or false");
      return j;
    case "string":
      if (typeof j !== "string")
        throw new Error("protobuf: string field expects a string");
      validateUtf16(j);
      return j;
    case "bytes":
      if (typeof j !== "string")
        throw new Error("protobuf: bytes field expects a base64 string");
      return base64Decode(j);
  }
}
function enumToJson(e, v) {
  if (e.fullName === "google.protobuf.NullValue")
    return null;
  return v;
}
function enumFromJson(e, j, ctx) {
  if (e.fullName === "google.protobuf.NullValue") {
    if (j !== null && j !== "NULL_VALUE")
      throw new Error("protobuf: NullValue expects null");
    return "NULL_VALUE";
  }
  if (typeof j === "number") {
    return e.byNumber.get(j) ?? j;
  }
  if (typeof j === "string") {
    if (e.byName.has(j))
      return j;
    if (ctx.ignoreUnknown)
      return DROP;
    throw new Error(`protobuf: unknown enum value "${j}" for ${e.fullName}`);
  }
  throw new Error(`protobuf: enum field expects a name string or number`);
}
function singleToJson(type, v, registry) {
  if (type.kind === "scalar")
    return scalarToJson(type.scalar, v);
  if (type.kind === "enum")
    return enumToJson(type.enum, v);
  return messageToJson(type.message, v, registry);
}
function fieldToJson(field, v, registry) {
  if (field.map) {
    const out = {};
    for (const [k, val] of Object.entries(v)) {
      out[k] = singleToJson(field.map.value.type, val, registry);
    }
    return out;
  }
  if (field.repeated)
    return v.map((e) => singleToJson(field.type, e, registry));
  return singleToJson(field.type, v, registry);
}
function isJsonOmittable(field, v) {
  if (field.explicitPresence)
    return false;
  if (field.map)
    return typeof v === "object" && v !== null && Object.keys(v).length === 0;
  if (field.repeated)
    return Array.isArray(v) && v.length === 0;
  if (field.type.kind === "scalar") {
    const t = field.type.scalar;
    if (BIGINT_SCALARS.has(t))
      return BigInt(v) === 0n;
    switch (t) {
      case "bool":
        return v === false;
      case "string":
        return v === "";
      case "bytes":
        return v.length === 0;
      default:
        return v === 0;
    }
  }
  if (field.type.kind === "enum") {
    const e = field.type.enum;
    return typeof v === "number" ? v === 0 : v === e.byNumber.get(0);
  }
  return false;
}
function messageToJson(message, value, registry) {
  switch (message.fullName) {
    case "google.protobuf.Timestamp":
      return timestampToJson(value);
    case "google.protobuf.Duration":
      return durationToJson(value);
    case "google.protobuf.FieldMask":
      return fieldMaskToJson(value);
    case "google.protobuf.Struct":
      return structToJson(value, registry);
    case "google.protobuf.Value":
      return valueToJson(value, registry);
    case "google.protobuf.ListValue":
      return listValueToJson(value, registry);
    case "google.protobuf.Any":
      return anyToJson(value, registry);
    case "google.protobuf.Empty":
      return {};
  }
  if (WRAPPERS.has(message.fullName))
    return wrapperToJson(message, value);
  const out = {};
  for (const field of message.fields) {
    const v = value[field.jsonName];
    if (v === undefined)
      continue;
    if (isJsonOmittable(field, v))
      continue;
    out[field.jsonName] = fieldToJson(field, v, registry);
  }
  return out;
}
function singleFromJson(type, j, ctx) {
  if (j === null) {
    if (type.kind === "message" && type.message.fullName === "google.protobuf.Value")
      return valueFromJson(null, ctx);
    if (type.kind === "enum" && type.enum.fullName === "google.protobuf.NullValue")
      return "NULL_VALUE";
    throw new Error("protobuf: null is not a valid value here");
  }
  if (type.kind === "scalar")
    return scalarFromJson(type.scalar, j);
  if (type.kind === "enum")
    return enumFromJson(type.enum, j, ctx);
  return messageFromJsonCtx(type.message, j, ctx);
}
function fieldFromJson(field, j, ctx) {
  if (field.map) {
    if (typeof j !== "object" || j === null || Array.isArray(j)) {
      throw new Error(`protobuf: map field "${field.name}" JSON must be an object`);
    }
    const out = {};
    for (const [k, val] of Object.entries(j)) {
      const v = singleFromJson(field.map.value.type, val, ctx);
      if (v !== DROP)
        out[k] = v;
    }
    return out;
  }
  if (field.repeated) {
    if (!Array.isArray(j))
      throw new Error(`protobuf: repeated field "${field.name}" JSON must be an array`);
    const out = [];
    for (const e of j) {
      const v = singleFromJson(field.type, e, ctx);
      if (v !== DROP)
        out.push(v);
    }
    return out;
  }
  return singleFromJson(field.type, j, ctx);
}
function isNullableField(type) {
  return type.kind === "message" && type.message.fullName === "google.protobuf.Value" || type.kind === "enum" && type.enum.fullName === "google.protobuf.NullValue";
}
function messageFromJsonCtx(message, j, ctx) {
  switch (message.fullName) {
    case "google.protobuf.Timestamp":
      return timestampFromJson(j);
    case "google.protobuf.Duration":
      return durationFromJson(j);
    case "google.protobuf.FieldMask":
      return fieldMaskFromJson(j);
    case "google.protobuf.Struct":
      if (j === null || typeof j !== "object" || Array.isArray(j))
        throw new Error("protobuf: Struct JSON must be an object");
      return structFromJson(j, ctx);
    case "google.protobuf.Value":
      return valueFromJson(j, ctx);
    case "google.protobuf.ListValue":
      return listValueFromJson(j, ctx);
    case "google.protobuf.Any":
      return anyFromJson(j, ctx);
    case "google.protobuf.Empty":
      return {};
  }
  if (WRAPPERS.has(message.fullName))
    return wrapperFromJson(message, j);
  if (j === null || typeof j !== "object" || Array.isArray(j)) {
    throw new Error(`protobuf: message "${message.fullName}" JSON must be an object`);
  }
  const out = {};
  const seenOneof = new Set;
  for (const [k, val] of Object.entries(j)) {
    const field = message.fields.find((f) => f.jsonName === k || f.name === k);
    if (!field) {
      if (ctx.ignoreUnknown)
        continue;
      throw new Error(`protobuf: unknown field "${k}" in ${message.fullName}`);
    }
    if (val === null && !isNullableField(field.type))
      continue;
    if (field.oneofIndex >= 0) {
      if (seenOneof.has(field.oneofIndex))
        throw new Error(`protobuf: multiple values for oneof "${message.oneofs[field.oneofIndex].name}"`);
      seenOneof.add(field.oneofIndex);
    }
    const v = fieldFromJson(field, val, ctx);
    if (v !== DROP)
      out[field.jsonName] = v;
  }
  return out;
}
function messageFromJson(message, j, registry, opts = {}) {
  return messageFromJsonCtx(message, j, { registry, ignoreUnknown: opts.ignoreUnknownFields ?? false });
}

// serialization/protobuf/stream.ts
function pullFrom(source) {
  if (source instanceof Uint8Array) {
    let sent = false;
    return async () => sent ? null : (sent = true, source);
  }
  const s = source;
  if (typeof s.getReader === "function") {
    const r = source.getReader();
    return async () => {
      const { done, value } = await r.read();
      return done || value === undefined ? null : value;
    };
  }
  if (typeof s[Symbol.asyncIterator] === "function") {
    const it = source[Symbol.asyncIterator]();
    return async () => {
      const { done, value } = await it.next();
      return done ? null : value;
    };
  }
  if (typeof s[Symbol.iterator] === "function") {
    const it = source[Symbol.iterator]();
    return async () => {
      const { done, value } = it.next();
      return done ? null : value;
    };
  }
  throw new Error("protobuf: decodeStream source must be a ReadableStream or (async) iterable of Uint8Array");
}

class ByteStream {
  pull;
  buf = new Uint8Array(0);
  pos = 0;
  done = false;
  constructor(pull) {
    this.pull = pull;
  }
  async more() {
    if (this.done)
      return false;
    const chunk = await this.pull();
    if (chunk == null) {
      this.done = true;
      return false;
    }
    if (chunk.length === 0)
      return this.more();
    const rest = this.buf.subarray(this.pos);
    const next = new Uint8Array(rest.length + chunk.length);
    next.set(rest);
    next.set(chunk, rest.length);
    this.buf = next;
    this.pos = 0;
    return true;
  }
  async ensure(n) {
    while (this.buf.length - this.pos < n)
      if (!await this.more())
        return false;
    return true;
  }
  async atEnd() {
    if (this.buf.length > this.pos)
      return false;
    return !await this.more();
  }
  async varint() {
    let result = 0n;
    let shift = 0n;
    let count = 0;
    for (;; ) {
      if (this.pos >= this.buf.length && !await this.more()) {
        throw new Error("protobuf: truncated varint in stream");
      }
      if (++count > 10)
        throw new Error("protobuf: varint is too long");
      const b = this.buf[this.pos++];
      result |= BigInt(b & 127) << shift;
      shift += 7n;
      if (!(b & 128))
        break;
    }
    return result;
  }
  async tag() {
    if (await this.atEnd())
      return null;
    const v = Number(await this.varint());
    return { fieldNo: v >>> 3, wire: v & 7 };
  }
  async bytes(n) {
    if (!await this.ensure(n))
      throw new Error("protobuf: truncated length-delimited value in stream");
    const out = this.buf.subarray(this.pos, this.pos + n);
    this.pos += n;
    return out;
  }
  async skip(wire, depth = 0) {
    switch (wire) {
      case 0:
        await this.varint();
        break;
      case 1:
        await this.bytes(8);
        break;
      case WIRE_LEN:
        await this.bytes(Number(await this.varint()));
        break;
      case 5:
        await this.bytes(4);
        break;
      case 3: {
        if (depth > 100)
          throw new Error("protobuf: group nesting exceeds maximum depth in stream");
        for (;; ) {
          const t = await this.tag();
          if (!t)
            throw new Error("protobuf: truncated group in stream");
          if (t.wire === WIRE_EGROUP)
            break;
          await this.skip(t.wire, depth + 1);
        }
        break;
      }
      case WIRE_EGROUP:
        break;
      default:
        throw new Error(`protobuf: cannot skip wire type ${wire} in stream`);
    }
  }
}
async function* decodeStream(field, source) {
  if (field.type.kind !== "message")
    return;
  const element = field.type.message;
  const reader = new ByteStream(pullFrom(source));
  for (;; ) {
    const t = await reader.tag();
    if (!t)
      break;
    if (t.fieldNo === field.number && t.wire === WIRE_LEN) {
      const len = Number(await reader.varint());
      yield decode(element, new Reader(await reader.bytes(len)));
    } else {
      await reader.skip(t.wire);
    }
  }
}
async function* decodeDelimitedStream(message, source) {
  const reader = new ByteStream(pullFrom(source));
  while (!await reader.atEnd()) {
    const len = Number(await reader.varint());
    yield decode(message, new Reader(await reader.bytes(len)));
  }
}

// serialization/protobuf/wkt.ts
var WKT = {
  "google/protobuf/timestamp.proto": `
    syntax = "proto3"; package google.protobuf;
    message Timestamp { int64 seconds = 1; int32 nanos = 2; }
  `,
  "google/protobuf/duration.proto": `
    syntax = "proto3"; package google.protobuf;
    message Duration { int64 seconds = 1; int32 nanos = 2; }
  `,
  "google/protobuf/empty.proto": `
    syntax = "proto3"; package google.protobuf;
    message Empty {}
  `,
  "google/protobuf/field_mask.proto": `
    syntax = "proto3"; package google.protobuf;
    message FieldMask { repeated string paths = 1; }
  `,
  "google/protobuf/any.proto": `
    syntax = "proto3"; package google.protobuf;
    message Any { string type_url = 1; bytes value = 2; }
  `,
  "google/protobuf/wrappers.proto": `
    syntax = "proto3"; package google.protobuf;
    message DoubleValue { double value = 1; }
    message FloatValue { float value = 1; }
    message Int64Value { int64 value = 1; }
    message UInt64Value { uint64 value = 1; }
    message Int32Value { int32 value = 1; }
    message UInt32Value { uint32 value = 1; }
    message BoolValue { bool value = 1; }
    message StringValue { string value = 1; }
    message BytesValue { bytes value = 1; }
  `,
  "google/protobuf/struct.proto": `
    syntax = "proto3"; package google.protobuf;
    message Struct { map<string, Value> fields = 1; }
    message Value {
      oneof kind {
        NullValue null_value = 1;
        double number_value = 2;
        string string_value = 3;
        bool bool_value = 4;
        Struct struct_value = 5;
        ListValue list_value = 6;
      }
    }
    message ListValue { repeated Value values = 1; }
    enum NullValue { NULL_VALUE = 0; }
  `
};

// serialization/protobuf/descriptor_set.ts
var DESCRIPTOR_PROTO = `
syntax = "proto3";
package google.protobuf;

message FileDescriptorSet { repeated FileDescriptorProto file = 1; }

message FileDescriptorProto {
  string name = 1;
  string package = 2;
  repeated string dependency = 3;
  repeated DescriptorProto message_type = 4;
  repeated EnumDescriptorProto enum_type = 5;
  FileOptions options = 8;
  string syntax = 12;
  int32 edition = 14;
}

message DescriptorProto {
  string name = 1;
  repeated FieldDescriptorProto field = 2;
  repeated DescriptorProto nested_type = 3;
  repeated EnumDescriptorProto enum_type = 4;
  MessageOptions options = 7;
  repeated OneofDescriptorProto oneof_decl = 8;
}

message FieldDescriptorProto {
  enum Label { LABEL_UNKNOWN = 0; LABEL_OPTIONAL = 1; LABEL_REQUIRED = 2; LABEL_REPEATED = 3; }
  enum Type {
    TYPE_UNKNOWN = 0; TYPE_DOUBLE = 1; TYPE_FLOAT = 2; TYPE_INT64 = 3; TYPE_UINT64 = 4;
    TYPE_INT32 = 5; TYPE_FIXED64 = 6; TYPE_FIXED32 = 7; TYPE_BOOL = 8; TYPE_STRING = 9;
    TYPE_GROUP = 10; TYPE_MESSAGE = 11; TYPE_BYTES = 12; TYPE_UINT32 = 13; TYPE_ENUM = 14;
    TYPE_SFIXED32 = 15; TYPE_SFIXED64 = 16; TYPE_SINT32 = 17; TYPE_SINT64 = 18;
  }
  string name = 1;
  int32 number = 3;
  Label label = 4;
  Type type = 5;
  string type_name = 6;
  FieldOptions options = 8;
  int32 oneof_index = 9;
  string json_name = 10;
  bool proto3_optional = 17;
}

message OneofDescriptorProto { string name = 1; OneofOptions options = 2; }
message EnumDescriptorProto { string name = 1; repeated EnumValueDescriptorProto value = 2; EnumOptions options = 3; }
message EnumValueDescriptorProto { string name = 1; int32 number = 2; }

message FeatureSet {
  enum FieldPresence { FIELD_PRESENCE_UNKNOWN = 0; EXPLICIT = 1; IMPLICIT = 2; LEGACY_REQUIRED = 3; }
  enum EnumType { ENUM_TYPE_UNKNOWN = 0; OPEN = 1; CLOSED = 2; }
  enum RepeatedFieldEncoding { REPEATED_FIELD_ENCODING_UNKNOWN = 0; PACKED = 1; EXPANDED = 2; }
  enum MessageEncoding { MESSAGE_ENCODING_UNKNOWN = 0; LENGTH_PREFIXED = 1; DELIMITED = 2; }
  FieldPresence field_presence = 1;
  EnumType enum_type = 2;
  RepeatedFieldEncoding repeated_field_encoding = 3;
  MessageEncoding message_encoding = 5;
}

message FileOptions { FeatureSet features = 50; }
message MessageOptions { bool map_entry = 7; FeatureSet features = 12; }
message FieldOptions { bool packed = 2; FeatureSet features = 21; }
message EnumOptions { FeatureSet features = 7; }
message OneofOptions { FeatureSet features = 1; }
`;
var SCALAR_BY_TYPE = {
  TYPE_DOUBLE: "double",
  TYPE_FLOAT: "float",
  TYPE_INT64: "int64",
  TYPE_UINT64: "uint64",
  TYPE_INT32: "int32",
  TYPE_FIXED64: "fixed64",
  TYPE_FIXED32: "fixed32",
  TYPE_BOOL: "bool",
  TYPE_STRING: "string",
  TYPE_BYTES: "bytes",
  TYPE_UINT32: "uint32",
  TYPE_SFIXED32: "sfixed32",
  TYPE_SFIXED64: "sfixed64",
  TYPE_SINT32: "sint32",
  TYPE_SINT64: "sint64"
};
var descRegistry = null;
function descriptorRegistry() {
  return descRegistry ??= link([parseProto(DESCRIPTOR_PROTO)]);
}
function mapFeatures(f) {
  const out = {};
  if (!f)
    return out;
  if (f.fieldPresence && f.fieldPresence !== "FIELD_PRESENCE_UNKNOWN")
    out.fieldPresence = f.fieldPresence;
  if (f.enumType && f.enumType !== "ENUM_TYPE_UNKNOWN")
    out.enumType = f.enumType;
  if (f.repeatedFieldEncoding && f.repeatedFieldEncoding !== "REPEATED_FIELD_ENCODING_UNKNOWN")
    out.repeatedEncoding = f.repeatedFieldEncoding;
  if (f.messageEncoding && f.messageEncoding !== "MESSAGE_ENCODING_UNKNOWN")
    out.messageEncoding = f.messageEncoding;
  return out;
}
function typeRef(f) {
  if (f.type === "TYPE_MESSAGE" || f.type === "TYPE_ENUM" || f.type === "TYPE_GROUP")
    return f.typeName;
  const scalar = typeof f.type === "string" ? SCALAR_BY_TYPE[f.type] : undefined;
  if (!scalar)
    throw new Error(`protobuf: unsupported field type ${f.type} in descriptor set`);
  return scalar;
}
function mapField(f, mapEntries) {
  const repeated = f.label === "LABEL_REPEATED";
  const entryName = typeof f.typeName === "string" ? f.typeName.split(".").pop() : "";
  if (repeated && f.type === "TYPE_MESSAGE" && mapEntries.has(entryName)) {
    const e = mapEntries.get(entryName);
    return {
      label: "singular",
      typeName: "",
      name: f.name,
      number: f.number,
      jsonName: f.jsonName,
      features: mapFeatures(f.options?.features),
      map: e
    };
  }
  const label = repeated ? "repeated" : f.label === "LABEL_REQUIRED" ? "required" : f.proto3Optional ? "optional" : "singular";
  const features = mapFeatures(f.options?.features);
  if (f.type === "TYPE_GROUP")
    features.messageEncoding = "DELIMITED";
  return {
    label,
    typeName: typeRef(f),
    name: f.name,
    number: f.number,
    jsonName: f.jsonName,
    packedOption: f.options?.packed,
    features
  };
}
function mapEnum(e) {
  return {
    name: e.name,
    values: (e.value ?? []).map((v) => ({ name: v.name, number: v.number ?? 0 })),
    features: mapFeatures(e.options?.features)
  };
}
function mapMessage(d) {
  const nested = d.nestedType ?? [];
  const mapEntries = new Map;
  for (const nt of nested) {
    if (nt.options?.mapEntry) {
      const field = nt.field ?? [];
      const k = field.find((x) => x.number === 1);
      const v = field.find((x) => x.number === 2);
      mapEntries.set(nt.name, { key: typeRef(k), value: typeRef(v) });
    }
  }
  const oneofDecl = d.oneofDecl ?? [];
  const realOneof = new Map;
  const fields = [];
  for (const f of d.field ?? []) {
    const af = mapField(f, mapEntries);
    if (!f.proto3Optional && f.oneofIndex != null) {
      let arr = realOneof.get(f.oneofIndex);
      if (!arr)
        realOneof.set(f.oneofIndex, arr = []);
      arr.push(af);
    } else {
      fields.push(af);
    }
  }
  const oneofs = [...realOneof.keys()].sort((a, b) => a - b).map((idx) => ({ name: oneofDecl[idx]?.name ?? `oneof_${idx}`, fields: realOneof.get(idx) }));
  return {
    name: d.name,
    fields,
    oneofs,
    messages: nested.filter((nt) => !nt.options?.mapEntry).map(mapMessage),
    enums: (d.enumType ?? []).map(mapEnum),
    features: mapFeatures(d.options?.features)
  };
}
function mapSyntax(syntax, edition) {
  if (syntax === "editions") {
    if (edition === 1000)
      return "2023";
    if (edition === 1001)
      return "2024";
    throw new Error(`protobuf: descriptor set uses an unsupported edition (${edition ?? "unknown"})`);
  }
  if (syntax === "proto3")
    return "proto3";
  if (syntax === undefined || syntax === "" || syntax === "proto2")
    return "proto2";
  throw new Error(`protobuf: descriptor set uses unsupported syntax "${syntax}"`);
}
function mapFile(fd) {
  return {
    syntax: mapSyntax(fd.syntax, fd.edition),
    package: fd.package ?? "",
    imports: fd.dependency ?? [],
    features: mapFeatures(fd.options?.features),
    messages: (fd.messageType ?? []).map(mapMessage),
    enums: (fd.enumType ?? []).map(mapEnum)
  };
}
function parseDescriptorSet(bytes) {
  const reg = descriptorRegistry();
  const setType = reg.messages.get("google.protobuf.FileDescriptorSet");
  const fds = decode(setType, new Reader(bytes));
  const files = fds.file ?? [];
  const present = new Set(files.map((f) => f.name));
  const parsed = files.map(mapFile);
  for (const [name, src] of Object.entries(WKT)) {
    if (!present.has(name))
      parsed.push(parseProto(src));
  }
  return parsed;
}

// serialization/protobuf/schema.ts
class Schema {
  registry;
  constructor(proto, _opts = {}) {
    const sources = typeof proto === "string" ? { "__main__.proto": proto } : { ...proto };
    const parsed = [];
    const seen = new Set;
    const toParse = Object.keys(sources);
    while (toParse.length) {
      const name = toParse.shift();
      if (seen.has(name))
        continue;
      seen.add(name);
      const src = sources[name] ?? WKT[name];
      if (src == null)
        throw new Error(`protobuf: cannot resolve import "${name}"`);
      const pf = parseProto(src);
      parsed.push(pf);
      for (const imp of pf.imports)
        if (!seen.has(imp))
          toParse.push(imp);
    }
    this.registry = link(parsed);
  }
  static fromDescriptorSet(descriptorSet) {
    const schema = Object.create(Schema.prototype);
    schema.registry = link(parseDescriptorSet(descriptorSet));
    return schema;
  }
  decode(messageName, bytes) {
    const m = this.registry.messages.get(messageName);
    if (!m)
      throw new Error(`protobuf: unknown message "${messageName}"`);
    return decode(m, new Reader(bytes));
  }
  encode(messageName, value) {
    const m = this.registry.messages.get(messageName);
    if (!m)
      throw new Error(`protobuf: unknown message "${messageName}"`);
    const w = new Writer;
    encode(m, value, w);
    return w.finish();
  }
  encodeDelimited(messageName, value) {
    const body = this.encode(messageName, value);
    const w = new Writer;
    w.uint32(body.length);
    w.raw(body);
    return w.finish();
  }
  toJson(messageName, value) {
    const m = this.registry.messages.get(messageName);
    if (!m)
      throw new Error(`protobuf: unknown message "${messageName}"`);
    return messageToJson(m, value, this.registry);
  }
  fromJson(messageName, json, options = {}) {
    const m = this.registry.messages.get(messageName);
    if (!m)
      throw new Error(`protobuf: unknown message "${messageName}"`);
    return messageFromJson(m, json, this.registry, options);
  }
  decodeStream(messageName, fieldName, source) {
    const m = this.registry.messages.get(messageName);
    if (!m)
      throw new Error(`protobuf: unknown message "${messageName}"`);
    const field = m.fields.find((f) => f.jsonName === fieldName || f.name === fieldName);
    if (!field)
      throw new Error(`protobuf: unknown field "${fieldName}" in ${messageName}`);
    if (!field.repeated || field.type.kind !== "message") {
      throw new Error(`protobuf: decodeStream requires a repeated message field; "${fieldName}" is not one`);
    }
    if (field.delimited) {
      throw new Error(`protobuf: decodeStream does not support delimited (group) fields`);
    }
    return decodeStream(field, source);
  }
  decodeDelimited(messageName, source) {
    const m = this.registry.messages.get(messageName);
    if (!m)
      throw new Error(`protobuf: unknown message "${messageName}"`);
    return decodeDelimitedStream(m, source);
  }
}
var Protobuf = { Schema };

// serialization/index.ts
var ops = globalThis.__ops;
var {
  xml_parse,
  xml_validate,
  xml_build,
  yaml_parse,
  yaml_validate,
  yaml_build,
  toml_parse,
  toml_validate,
  toml_build,
  msgpack_parse,
  msgpack_validate,
  msgpack_build,
  xml_stream_new,
  xml_stream_push,
  xml_stream_close
} = ops;
function validateWith(fn, input, options = {}) {
  const result = fn(input);
  if (result === true)
    return options.detailed ? { valid: true } : true;
  return options.detailed ? { valid: false, error: result } : false;
}
var TOML = {
  validate: (toml, options) => validateWith(toml_validate, toml, options),
  parse: (toml) => toml_parse(toml),
  build: (obj) => toml_build(obj)
};
var YAML = {
  validate: (yaml, options) => validateWith(yaml_validate, yaml, options),
  parse: (yaml) => yaml_parse(yaml),
  build: (obj) => yaml_build(obj)
};
var MessagePack = {
  validate: (msgpack, options) => validateWith(msgpack_validate, msgpack, options),
  decode: (msgpack) => JSON.parse(msgpack_parse(msgpack)),
  encode: (obj) => msgpack_build(obj)
};

class JSONLDecoderStream extends TransformStream {
  onError;
  constructor(options = {}) {
    let buffer = "";
    const decoder = new TextDecoder;
    const skipInvalid = !!options.skipInvalid;
    let lineNumber = 0;
    let errorCallback = null;
    const emit = (controller, raw) => {
      const trimmed = raw.trim();
      if (!trimmed)
        return;
      try {
        controller.enqueue(JSON.parse(trimmed));
      } catch (err) {
        if (skipInvalid)
          errorCallback?.({ line: lineNumber, raw: trimmed, cause: err });
        else
          controller.error(new SyntaxError(`Invalid JSONL line ${lineNumber}: ${err.message}`));
      }
    };
    super({
      transform(chunk, controller) {
        const text = typeof chunk === "string" ? chunk : decoder.decode(chunk, { stream: true });
        buffer += text;
        const lines = buffer.split(`
`);
        buffer = lines.pop() ?? "";
        for (const line of lines) {
          lineNumber++;
          emit(controller, line);
        }
      },
      flush(controller) {
        if (buffer) {
          lineNumber++;
          emit(controller, buffer);
        }
      }
    });
    this.onError = (cb) => {
      errorCallback = cb;
    };
  }
}

class JSONLEncoderStream extends TransformStream {
  _writer = null;
  constructor() {
    super({
      transform(chunk, controller) {
        try {
          controller.enqueue(JSON.stringify(chunk) + `
`);
        } catch (err) {
          controller.error(new TypeError(`Cannot serialize to JSONL: ${err.message}`));
        }
      }
    });
  }
  pipeTo(destination, options) {
    return this.readable.pipeTo(destination, options);
  }
  write(chunk) {
    this._writer ??= this.writable.getWriter();
    return this._writer.write(chunk);
  }
  close() {
    return (this._writer ?? this.writable.getWriter()).close();
  }
}
var JSONL = { DecoderStream: JSONLDecoderStream, EncoderStream: JSONLEncoderStream };

class XMLDecoderStream extends TransformStream {
  constructor() {
    let streamId = null;
    super({
      start() {
        streamId = xml_stream_new();
      },
      transform(chunk, controller) {
        const text = typeof chunk === "string" ? chunk : new TextDecoder().decode(chunk);
        for (const obj of xml_stream_push(streamId, text))
          controller.enqueue(obj);
      },
      flush() {
        xml_stream_close(streamId);
      }
    });
  }
}
var XML = {
  validate: (xml, options) => validateWith(xml_validate, xml, options),
  parse: (xml) => xml_parse(xml),
  build: (obj) => xml_build(obj),
  DecoderStream: XMLDecoderStream
};
export {
  YAML,
  XML,
  TOML,
  Protobuf,
  MessagePack,
  JSONL
};
