// @generated by `bun run build` in crates/runtime/js — do not edit by hand.
// serialization/protobuf/lexer.ts
var IDENT_START = /[A-Za-z_]/;
var IDENT_PART = /[A-Za-z0-9_]/;
var DIGIT = /[0-9]/;

class Lexer {
  src;
  pos = 0;
  line = 1;
  peeked = null;
  constructor(src) {
    this.src = src;
  }
  peek() {
    return this.peeked ??= this.scan();
  }
  next() {
    if (this.peeked) {
      const t = this.peeked;
      this.peeked = null;
      return t;
    }
    return this.scan();
  }
  scan() {
    this.skipTrivia();
    if (this.pos >= this.src.length)
      return { kind: "eof", value: "", line: this.line };
    const ch = this.src[this.pos];
    const line = this.line;
    if (IDENT_START.test(ch)) {
      const start = this.pos;
      while (this.pos < this.src.length && IDENT_PART.test(this.src[this.pos]))
        this.pos++;
      return { kind: "ident", value: this.src.slice(start, this.pos), line };
    }
    if (DIGIT.test(ch) || ch === "." && DIGIT.test(this.src[this.pos + 1] ?? "")) {
      return { kind: "num", value: this.scanNumber(), line };
    }
    if (ch === '"' || ch === "'") {
      return { kind: "str", value: this.scanString(ch), line };
    }
    this.pos++;
    return { kind: "sym", value: ch, line };
  }
  scanNumber() {
    const start = this.pos;
    if (this.src[this.pos] === "0" && (this.src[this.pos + 1] === "x" || this.src[this.pos + 1] === "X")) {
      this.pos += 2;
      while (this.pos < this.src.length && /[0-9a-fA-F]/.test(this.src[this.pos]))
        this.pos++;
      return this.src.slice(start, this.pos);
    }
    while (this.pos < this.src.length && /[0-9.eE+\-]/.test(this.src[this.pos])) {
      const c = this.src[this.pos];
      if ((c === "+" || c === "-") && !/[eE]/.test(this.src[this.pos - 1] ?? ""))
        break;
      this.pos++;
    }
    return this.src.slice(start, this.pos);
  }
  scanString(quote) {
    this.pos++;
    let out = "";
    while (this.pos < this.src.length) {
      const c = this.src[this.pos++];
      if (c === quote)
        return out;
      if (c === "\\") {
        const e = this.src[this.pos++];
        switch (e) {
          case "n":
            out += `
`;
            break;
          case "r":
            out += "\r";
            break;
          case "t":
            out += "\t";
            break;
          case "\\":
            out += "\\";
            break;
          case '"':
            out += '"';
            break;
          case "'":
            out += "'";
            break;
          case "0":
            out += "\x00";
            break;
          default:
            out += e;
            break;
        }
      } else {
        if (c === `
`)
          this.line++;
        out += c;
      }
    }
    throw new Error(`protobuf: unterminated string at line ${this.line}`);
  }
  skipTrivia() {
    while (this.pos < this.src.length) {
      const c = this.src[this.pos];
      if (c === `
`) {
        this.line++;
        this.pos++;
      } else if (c === " " || c === "\t" || c === "\r" || c === "\f" || c === "\v") {
        this.pos++;
      } else if (c === "/" && this.src[this.pos + 1] === "/") {
        while (this.pos < this.src.length && this.src[this.pos] !== `
`)
          this.pos++;
      } else if (c === "/" && this.src[this.pos + 1] === "*") {
        this.pos += 2;
        while (this.pos < this.src.length && !(this.src[this.pos] === "*" && this.src[this.pos + 1] === "/")) {
          if (this.src[this.pos] === `
`)
            this.line++;
          this.pos++;
        }
        this.pos += 2;
      } else {
        break;
      }
    }
  }
}

// serialization/protobuf/features.ts
function baseFeatures(syntax) {
  if (syntax === "proto3") {
    return { fieldPresence: "IMPLICIT", repeatedEncoding: "PACKED", enumType: "OPEN" };
  }
  return { fieldPresence: "EXPLICIT", repeatedEncoding: "PACKED", enumType: "OPEN" };
}
function mergeFeatures(base, over) {
  if (!over)
    return base;
  return {
    fieldPresence: over.fieldPresence ?? base.fieldPresence,
    repeatedEncoding: over.repeatedEncoding ?? base.repeatedEncoding,
    enumType: over.enumType ?? base.enumType
  };
}
function featureFromOption(key, value) {
  switch (key) {
    case "features.field_presence":
      return { fieldPresence: value };
    case "features.repeated_field_encoding":
      return { repeatedEncoding: value };
    case "features.enum_type":
      return { enumType: value };
    default:
      return null;
  }
}

// serialization/protobuf/parser.ts
var SCALARS = new Set([
  "double",
  "float",
  "int32",
  "int64",
  "uint32",
  "uint64",
  "sint32",
  "sint64",
  "fixed32",
  "fixed64",
  "sfixed32",
  "sfixed64",
  "bool",
  "string",
  "bytes"
]);
function parseProto(source) {
  return new Parser(source).parseFile();
}

class Parser {
  lx;
  constructor(source) {
    this.lx = new Lexer(source);
  }
  err(msg, line) {
    throw new Error(`protobuf parse error${line ? ` (line ${line})` : ""}: ${msg}`);
  }
  expectSym(s) {
    const t = this.lx.next();
    if (t.kind !== "sym" || t.value !== s)
      this.err(`expected '${s}', got '${t.value}'`, t.line);
  }
  acceptSym(s) {
    const t = this.lx.peek();
    if (t.kind === "sym" && t.value === s) {
      this.lx.next();
      return true;
    }
    return false;
  }
  expectIdent() {
    const t = this.lx.next();
    if (t.kind !== "ident")
      this.err(`expected identifier, got '${t.value}'`, t.line);
    return t.value;
  }
  isKeyword(t, kw) {
    return t.kind === "ident" && t.value === kw;
  }
  parseFile() {
    const file = {
      syntax: "proto3",
      package: "",
      imports: [],
      features: {},
      messages: [],
      enums: []
    };
    let sawSyntax = false;
    for (;; ) {
      const t = this.lx.peek();
      if (t.kind === "eof")
        break;
      if (t.kind === "sym" && t.value === ";") {
        this.lx.next();
        continue;
      }
      if (t.kind !== "ident")
        this.err(`unexpected '${t.value}'`, t.line);
      switch (t.value) {
        case "syntax": {
          this.lx.next();
          this.expectSym("=");
          const v = this.expectStr();
          if (v !== "proto3" && v !== "proto2")
            this.err(`unknown syntax "${v}"`, t.line);
          if (v === "proto2")
            this.err("proto2 syntax is unsupported (use proto3 or edition 2023)", t.line);
          file.syntax = "proto3";
          this.expectSym(";");
          sawSyntax = true;
          break;
        }
        case "edition": {
          this.lx.next();
          this.expectSym("=");
          const v = this.expectStr();
          if (v !== "2023")
            this.err(`unsupported edition "${v}" (only 2023)`, t.line);
          file.syntax = "2023";
          this.expectSym(";");
          sawSyntax = true;
          break;
        }
        case "package":
          this.lx.next();
          file.package = this.parseQualifiedName();
          this.expectSym(";");
          break;
        case "import": {
          this.lx.next();
          const p = this.lx.peek();
          if (this.isKeyword(p, "public") || this.isKeyword(p, "weak"))
            this.lx.next();
          file.imports.push(this.expectStr());
          this.expectSym(";");
          break;
        }
        case "option": {
          this.lx.next();
          const { key, value } = this.parseOption();
          const f = featureFromOption(key, value);
          if (f)
            Object.assign(file.features, f);
          this.expectSym(";");
          break;
        }
        case "message":
          this.lx.next();
          file.messages.push(this.parseMessage());
          break;
        case "enum":
          this.lx.next();
          file.enums.push(this.parseEnum());
          break;
        case "service":
          this.lx.next();
          this.skipBlock();
          break;
        case "extend":
          this.lx.next();
          this.skipBlock();
          break;
        default:
          this.err(`unexpected '${t.value}' at top level`, t.line);
      }
    }
    return file;
  }
  parseMessage() {
    const name = this.expectIdent();
    const msg = { name, fields: [], oneofs: [], messages: [], enums: [], features: {} };
    this.expectSym("{");
    for (;; ) {
      const t = this.lx.peek();
      if (t.kind === "sym" && t.value === "}") {
        this.lx.next();
        break;
      }
      if (t.kind === "eof")
        this.err("unexpected EOF in message");
      if (t.kind === "sym" && t.value === ";") {
        this.lx.next();
        continue;
      }
      if (t.kind === "ident") {
        switch (t.value) {
          case "message":
            this.lx.next();
            msg.messages.push(this.parseMessage());
            continue;
          case "enum":
            this.lx.next();
            msg.enums.push(this.parseEnum());
            continue;
          case "oneof":
            this.lx.next();
            msg.oneofs.push(this.parseOneof());
            continue;
          case "option": {
            this.lx.next();
            const { key, value } = this.parseOption();
            const f = featureFromOption(key, value);
            if (f)
              Object.assign(msg.features, f);
            this.expectSym(";");
            continue;
          }
          case "reserved":
            this.lx.next();
            this.skipToSemicolon();
            continue;
          case "map":
            msg.fields.push(this.parseMapField());
            continue;
          case "required":
            this.err("proto2 'required' fields are unsupported", t.line);
          case "group":
            this.err("proto2 groups are unsupported", t.line);
          case "extensions":
            this.lx.next();
            this.skipToSemicolon();
            continue;
          case "extend":
            this.lx.next();
            this.skipBlock();
            continue;
        }
      }
      msg.fields.push(this.parseField());
    }
    return msg;
  }
  parseOneof() {
    const name = this.expectIdent();
    const oneof = { name, fields: [] };
    this.expectSym("{");
    for (;; ) {
      const t = this.lx.peek();
      if (t.kind === "sym" && t.value === "}") {
        this.lx.next();
        break;
      }
      if (t.kind === "sym" && t.value === ";") {
        this.lx.next();
        continue;
      }
      if (this.isKeyword(t, "option")) {
        this.lx.next();
        this.parseOption();
        this.expectSym(";");
        continue;
      }
      oneof.fields.push(this.parseField(true));
    }
    return oneof;
  }
  parseField(inOneof = false) {
    let label = "singular";
    const t = this.lx.peek();
    if (!inOneof && (t.value === "repeated" || t.value === "optional")) {
      label = t.value;
      this.lx.next();
    } else if (t.value === "repeated" || t.value === "optional") {
      this.err(`'${t.value}' is not allowed inside oneof`, t.line);
    }
    const typeName = this.parseQualifiedName();
    const name = this.expectIdent();
    this.expectSym("=");
    const number = this.parseInt32();
    const field = { label, typeName, name, number, features: {} };
    this.parseFieldOptions(field);
    this.expectSym(";");
    return field;
  }
  parseMapField() {
    this.lx.next();
    this.expectSym("<");
    const key = this.parseQualifiedName();
    this.expectSym(",");
    const value = this.parseQualifiedName();
    this.expectSym(">");
    const name = this.expectIdent();
    this.expectSym("=");
    const number = this.parseInt32();
    const field = { label: "repeated", typeName: "", name, number, features: {}, map: { key, value } };
    this.parseFieldOptions(field);
    this.expectSym(";");
    return field;
  }
  parseFieldOptions(field) {
    if (!this.acceptSym("["))
      return;
    for (;; ) {
      const { key, value } = this.parseOption();
      if (key === "json_name")
        field.jsonName = value;
      else if (key === "packed")
        field.packedOption = value === "true";
      else {
        const f = featureFromOption(key, value);
        if (f)
          Object.assign(field.features, f);
      }
      if (this.acceptSym(","))
        continue;
      this.expectSym("]");
      break;
    }
  }
  parseOption() {
    let key;
    if (this.acceptSym("(")) {
      this.parseQualifiedName();
      this.expectSym(")");
      while (this.acceptSym("."))
        this.expectIdent();
      key = "";
    } else {
      key = this.expectIdent();
      while (this.acceptSym("."))
        key += "." + this.expectIdent();
    }
    this.expectSym("=");
    const value = this.parseOptionValue();
    return { key, value };
  }
  parseOptionValue() {
    const t = this.lx.next();
    if (t.kind === "str")
      return t.value;
    if (t.kind === "ident" || t.kind === "num")
      return t.value;
    if (t.kind === "sym" && (t.value === "-" || t.value === "+")) {
      const num = this.lx.next();
      if (num.kind !== "num")
        this.err(`bad option value '${t.value}${num.value}'`, t.line);
      return (t.value === "-" ? "-" : "") + num.value;
    }
    if (t.kind === "sym" && t.value === "{") {
      let depth = 1;
      while (depth > 0) {
        const n = this.lx.next();
        if (n.kind === "eof")
          this.err("unexpected EOF in option");
        if (n.kind === "sym" && n.value === "{")
          depth++;
        else if (n.kind === "sym" && n.value === "}")
          depth--;
      }
      return "";
    }
    this.err(`bad option value '${t.value}'`, t.line);
  }
  parseEnum() {
    const name = this.expectIdent();
    const en = { name, values: [], features: {} };
    this.expectSym("{");
    for (;; ) {
      const t = this.lx.peek();
      if (t.kind === "sym" && t.value === "}") {
        this.lx.next();
        break;
      }
      if (t.kind === "sym" && t.value === ";") {
        this.lx.next();
        continue;
      }
      if (this.isKeyword(t, "option")) {
        this.lx.next();
        const { key, value } = this.parseOption();
        const f = featureFromOption(key, value);
        if (f)
          Object.assign(en.features, f);
        this.expectSym(";");
        continue;
      }
      if (this.isKeyword(t, "reserved")) {
        this.lx.next();
        this.skipToSemicolon();
        continue;
      }
      const vname = this.expectIdent();
      this.expectSym("=");
      const num = this.parseInt32();
      if (this.acceptSym("[")) {
        for (;; ) {
          this.parseOption();
          if (this.acceptSym(","))
            continue;
          this.expectSym("]");
          break;
        }
      }
      this.expectSym(";");
      en.values.push({ name: vname, number: num });
    }
    return en;
  }
  expectStr() {
    const t = this.lx.next();
    if (t.kind !== "str")
      this.err(`expected string, got '${t.value}'`, t.line);
    return t.value;
  }
  parseInt32() {
    let sign = 1;
    const s = this.lx.peek();
    if (s.kind === "sym" && (s.value === "-" || s.value === "+")) {
      this.lx.next();
      sign = s.value === "-" ? -1 : 1;
    }
    const t = this.lx.next();
    if (t.kind !== "num")
      this.err(`expected number, got '${t.value}'`, t.line);
    const n = t.value.startsWith("0x") || t.value.startsWith("0X") ? parseInt(t.value, 16) : parseInt(t.value, 10);
    if (!Number.isFinite(n))
      this.err(`bad number '${t.value}'`, t.line);
    return sign * n;
  }
  parseQualifiedName() {
    let name = "";
    if (this.acceptSym("."))
      name = ".";
    name += this.expectIdent();
    while (this.lx.peek().kind === "sym" && this.lx.peek().value === ".") {
      this.lx.next();
      name += "." + this.expectIdent();
    }
    return name;
  }
  skipToSemicolon() {
    for (;; ) {
      const t = this.lx.next();
      if (t.kind === "eof")
        this.err("unexpected EOF");
      if (t.kind === "sym" && t.value === ";")
        return;
    }
  }
  skipBlock() {
    while (!(this.lx.peek().kind === "sym" && this.lx.peek().value === "{")) {
      if (this.lx.peek().kind === "eof")
        this.err("unexpected EOF");
      this.lx.next();
    }
    this.expectSym("{");
    let depth = 1;
    while (depth > 0) {
      const t = this.lx.next();
      if (t.kind === "eof")
        this.err("unexpected EOF in block");
      if (t.kind === "sym" && t.value === "{")
        depth++;
      else if (t.kind === "sym" && t.value === "}")
        depth--;
    }
  }
  static isScalar(name) {
    return SCALARS.has(name);
  }
}

// serialization/protobuf/link.ts
var PACKABLE_SCALARS = new Set([
  "double",
  "float",
  "int32",
  "int64",
  "uint32",
  "uint64",
  "sint32",
  "sint64",
  "fixed32",
  "fixed64",
  "sfixed32",
  "sfixed64",
  "bool"
]);
function camelCase(s) {
  let out = "";
  let up = false;
  for (const c of s) {
    if (c === "_")
      up = true;
    else {
      out += up ? c.toUpperCase() : c;
      up = false;
    }
  }
  return out;
}
function qualify(scope, name) {
  return scope ? scope + "." + name : name;
}
function link(files) {
  const messages = new Map;
  const enums = new Map;
  const jobs = [];
  function registerEnum(ast, scope, inherited) {
    const fullName = qualify(scope, ast.name);
    const closed = mergeFeatures(inherited, ast.features).enumType === "CLOSED";
    const byNumber = new Map;
    const byName = new Map;
    for (const v of ast.values) {
      if (!byNumber.has(v.number))
        byNumber.set(v.number, v.name);
      byName.set(v.name, v.number);
    }
    enums.set(fullName, { name: ast.name, fullName, values: ast.values, byNumber, byName, closed });
  }
  function registerMessage(ast, scope, inherited) {
    const fullName = qualify(scope, ast.name);
    const msgFeat = mergeFeatures(inherited, ast.features);
    const desc = {
      name: ast.name,
      fullName,
      fields: [],
      fieldByNumber: new Map,
      oneofs: [],
      isMapEntry: false
    };
    messages.set(fullName, desc);
    jobs.push({ ast, desc, scope: fullName, inherited: msgFeat });
    for (const e of ast.enums)
      registerEnum(e, fullName, msgFeat);
    for (const m of ast.messages)
      registerMessage(m, fullName, msgFeat);
  }
  for (const file of files) {
    const fileFeat = mergeFeatures(baseFeatures(file.syntax), file.features);
    for (const e of file.enums)
      registerEnum(e, file.package, fileFeat);
    for (const m of file.messages)
      registerMessage(m, file.package, fileFeat);
  }
  const registry = {
    messages,
    enums,
    get(n) {
      return messages.get(n) ?? enums.get(n);
    }
  };
  function resolveType(ref, scope) {
    if (Parser.isScalar(ref))
      return { kind: "scalar", scalar: ref };
    const abs = ref.startsWith(".");
    const bare = abs ? ref.slice(1) : ref;
    const tryNames = [];
    if (abs) {
      tryNames.push(bare);
    } else {
      const parts = scope ? scope.split(".") : [];
      for (let i = parts.length;i >= 0; i--) {
        tryNames.push([...parts.slice(0, i), bare].join("."));
      }
    }
    for (const n of tryNames) {
      const m = messages.get(n);
      if (m)
        return { kind: "message", message: m };
      const e = enums.get(n);
      if (e)
        return { kind: "enum", enum: e };
    }
    throw new Error(`protobuf: unknown type "${ref}" referenced from "${scope}"`);
  }
  function resolveField(ast, scope, inherited, oneofIndex) {
    const feat = mergeFeatures(inherited, ast.features);
    const jsonName = ast.jsonName ?? camelCase(ast.name);
    if (ast.map) {
      const keyType = resolveType(ast.map.key, scope);
      const valueType = resolveType(ast.map.value, scope);
      const key = { name: "key", jsonName: "key", number: 1, repeated: false, explicitPresence: false, packed: false, type: keyType, oneofIndex: -1 };
      const value = { name: "value", jsonName: "value", number: 2, repeated: false, explicitPresence: false, packed: false, type: valueType, oneofIndex: -1 };
      return { name: ast.name, jsonName, number: ast.number, repeated: false, explicitPresence: false, packed: false, type: valueType, oneofIndex: -1, map: { key, value } };
    }
    const type = resolveType(ast.typeName, scope);
    const repeated = ast.label === "repeated";
    let explicitPresence = false;
    let packed = false;
    if (repeated) {
      const packable = type.kind === "enum" || type.kind === "scalar" && PACKABLE_SCALARS.has(type.scalar);
      packed = packable && (ast.packedOption ?? feat.repeatedEncoding === "PACKED");
    } else if (type.kind === "message") {
      explicitPresence = true;
    } else if (ast.label === "optional" || oneofIndex >= 0) {
      explicitPresence = true;
    } else {
      explicitPresence = feat.fieldPresence === "EXPLICIT";
    }
    return { name: ast.name, jsonName, number: ast.number, repeated, explicitPresence, packed, type, oneofIndex };
  }
  for (const { ast, desc, scope, inherited } of jobs) {
    const add = (f) => {
      desc.fields.push(f);
      desc.fieldByNumber.set(f.number, f);
    };
    for (const af of ast.fields)
      add(resolveField(af, scope, inherited, -1));
    ast.oneofs.forEach((oneof, idx) => {
      const oneofIndex = desc.oneofs.length;
      const fieldNumbers = [];
      for (const af of oneof.fields) {
        const f = resolveField(af, scope, inherited, oneofIndex);
        add(f);
        fieldNumbers.push(f.number);
      }
      desc.oneofs.push({ name: oneof.name, fieldNumbers });
    });
  }
  return registry;
}

// serialization/protobuf/utf8.ts
function utf8Read(buf, start, end) {
  const len = end - start;
  if (len < 1)
    return "";
  let parts = null;
  const chunk = [];
  let i = 0;
  let t;
  let p = start;
  while (p < end) {
    t = buf[p++];
    if (t < 128) {
      chunk[i++] = t;
    } else if (t > 191 && t < 224) {
      chunk[i++] = (t & 31) << 6 | buf[p++] & 63;
    } else if (t > 239 && t < 365) {
      t = ((t & 7) << 18 | (buf[p++] & 63) << 12 | (buf[p++] & 63) << 6 | buf[p++] & 63) - 65536;
      chunk[i++] = 55296 + (t >> 10);
      chunk[i++] = 56320 + (t & 1023);
    } else {
      chunk[i++] = (t & 15) << 12 | (buf[p++] & 63) << 6 | buf[p++] & 63;
    }
    if (i > 8191) {
      (parts || (parts = [])).push(String.fromCharCode.apply(String, chunk));
      i = 0;
    }
  }
  if (parts) {
    if (i)
      parts.push(String.fromCharCode.apply(String, chunk.slice(0, i)));
    return parts.join("");
  }
  return String.fromCharCode.apply(String, chunk.slice(0, i));
}
function utf8Length(str) {
  let len = 0;
  for (let i = 0;i < str.length; i++) {
    const c = str.charCodeAt(i);
    if (c < 128)
      len += 1;
    else if (c < 2048)
      len += 2;
    else if (c >= 55296 && c <= 56319 && i + 1 < str.length && (str.charCodeAt(i + 1) & 64512) === 56320) {
      i++;
      len += 4;
    } else
      len += 3;
  }
  return len;
}
function utf8Write(str, buf, offset) {
  let p = offset;
  for (let i = 0;i < str.length; i++) {
    let c = str.charCodeAt(i);
    if (c < 128) {
      buf[p++] = c;
    } else if (c < 2048) {
      buf[p++] = c >> 6 | 192;
      buf[p++] = c & 63 | 128;
    } else if (c >= 55296 && c <= 56319 && i + 1 < str.length && (str.charCodeAt(i + 1) & 64512) === 56320) {
      c = 65536 + ((c & 1023) << 10) + (str.charCodeAt(++i) & 1023);
      buf[p++] = c >> 18 | 240;
      buf[p++] = c >> 12 & 63 | 128;
      buf[p++] = c >> 6 & 63 | 128;
      buf[p++] = c & 63 | 128;
    } else {
      buf[p++] = c >> 12 | 224;
      buf[p++] = c >> 6 & 63 | 128;
      buf[p++] = c & 63 | 128;
    }
  }
  return p;
}

// serialization/protobuf/reader.ts
var WIRE_VARINT = 0;
var WIRE_I64 = 1;
var WIRE_LEN = 2;
var WIRE_SGROUP = 3;
var WIRE_EGROUP = 4;
var WIRE_I32 = 5;

class Reader {
  buf;
  pos;
  end;
  view;
  constructor(buf, start = 0, end = buf.length) {
    this.buf = buf;
    this.pos = start;
    this.end = end;
    this.view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  }
  eof() {
    return this.pos >= this.end;
  }
  need(n) {
    if (this.pos + n > this.end)
      throw new Error("protobuf: unexpected end of input");
  }
  uint32() {
    let result = 0;
    let shift = 0;
    let count = 0;
    let b;
    do {
      if (this.pos >= this.end)
        throw new Error("protobuf: unexpected end of input (varint)");
      if (++count > 10)
        throw new Error("protobuf: varint is too long");
      b = this.buf[this.pos++];
      if (shift < 32)
        result = (result | (b & 127) << shift) >>> 0;
      shift += 7;
    } while (b & 128);
    return result >>> 0;
  }
  int32() {
    return this.uint32() | 0;
  }
  sint32() {
    const n = this.uint32();
    return n >>> 1 ^ -(n & 1);
  }
  varint64() {
    let result = 0n;
    let shift = 0n;
    let count = 0;
    let b;
    do {
      if (this.pos >= this.end)
        throw new Error("protobuf: unexpected end of input (varint)");
      if (++count > 10)
        throw new Error("protobuf: varint is too long");
      b = this.buf[this.pos++];
      result |= BigInt(b & 127) << shift;
      shift += 7n;
    } while (b & 128);
    return BigInt.asUintN(64, result);
  }
  int64() {
    return BigInt.asIntN(64, this.varint64());
  }
  uint64() {
    return this.varint64();
  }
  sint64() {
    const u = this.varint64();
    return BigInt.asIntN(64, u >> 1n ^ -(u & 1n));
  }
  bool() {
    return this.varint64() !== 0n;
  }
  fixed32() {
    this.need(4);
    const v = this.view.getUint32(this.pos, true);
    this.pos += 4;
    return v;
  }
  sfixed32() {
    this.need(4);
    const v = this.view.getInt32(this.pos, true);
    this.pos += 4;
    return v;
  }
  float() {
    this.need(4);
    const v = this.view.getFloat32(this.pos, true);
    this.pos += 4;
    return v;
  }
  fixed64() {
    this.need(8);
    const v = this.view.getBigUint64(this.pos, true);
    this.pos += 8;
    return v;
  }
  sfixed64() {
    this.need(8);
    const v = this.view.getBigInt64(this.pos, true);
    this.pos += 8;
    return v;
  }
  double() {
    this.need(8);
    const v = this.view.getFloat64(this.pos, true);
    this.pos += 8;
    return v;
  }
  string() {
    const len = this.uint32();
    this.need(len);
    const start = this.pos;
    this.pos += len;
    return utf8Read(this.buf, start, start + len);
  }
  bytes() {
    const len = this.uint32();
    this.need(len);
    const start = this.pos;
    this.pos += len;
    return this.buf.slice(start, start + len);
  }
  fork() {
    const len = this.uint32();
    this.need(len);
    const start = this.pos;
    this.pos += len;
    return new Reader(this.buf, start, start + len);
  }
  skip(wireType) {
    switch (wireType) {
      case WIRE_VARINT: {
        let b;
        do {
          if (this.pos >= this.end)
            throw new Error("protobuf: unexpected end of input (varint)");
          b = this.buf[this.pos++];
        } while (b & 128);
        break;
      }
      case WIRE_I64:
        this.need(8);
        this.pos += 8;
        break;
      case WIRE_LEN: {
        const len = this.uint32();
        this.need(len);
        this.pos += len;
        break;
      }
      case WIRE_I32:
        this.need(4);
        this.pos += 4;
        break;
      case WIRE_SGROUP: {
        for (;; ) {
          const tag = this.uint32();
          const wt = tag & 7;
          if (wt === WIRE_EGROUP)
            break;
          this.skip(wt);
        }
        break;
      }
      case WIRE_EGROUP:
        break;
      default:
        throw new Error(`protobuf: cannot skip wire type ${wireType}`);
    }
  }
  rawFrom(tagStart) {
    return this.buf.slice(tagStart, this.pos);
  }
}

// serialization/protobuf/decode.ts
var UNKNOWN = Symbol.for("esrun.protobuf.unknown");
function expectedWire(type) {
  if (type.kind === "message")
    return 2;
  if (type.kind === "enum")
    return 0;
  switch (type.scalar) {
    case "string":
    case "bytes":
      return 2;
    case "double":
    case "fixed64":
    case "sfixed64":
      return 1;
    case "float":
    case "fixed32":
    case "sfixed32":
      return 5;
    default:
      return 0;
  }
}
function readScalar(r, t) {
  switch (t) {
    case "double":
      return r.double();
    case "float":
      return r.float();
    case "int32":
      return r.int32();
    case "int64":
      return r.int64();
    case "uint32":
      return r.uint32();
    case "uint64":
      return r.uint64();
    case "sint32":
      return r.sint32();
    case "sint64":
      return r.sint64();
    case "fixed32":
      return r.fixed32();
    case "fixed64":
      return r.fixed64();
    case "sfixed32":
      return r.sfixed32();
    case "sfixed64":
      return r.sfixed64();
    case "bool":
      return r.bool();
    case "string":
      return r.string();
    case "bytes":
      return r.bytes();
  }
}
function readEnum(r, e) {
  const n = r.int32();
  return e.byNumber.get(n) ?? n;
}
function readSingle(r, type) {
  if (type.kind === "scalar")
    return readScalar(r, type.scalar);
  if (type.kind === "enum")
    return readEnum(r, type.enum);
  return decode(type.message, r.fork());
}
function decode(message, r, target) {
  const out = target ?? {};
  while (!r.eof()) {
    const tagStart = r.pos;
    const tag = r.uint32();
    const fieldNo = tag >>> 3;
    const wire = tag & 7;
    if (fieldNo === 0)
      throw new Error("protobuf: invalid field number 0");
    const field = message.fieldByNumber.get(fieldNo);
    if (!field) {
      r.skip(wire);
      (out[UNKNOWN] ?? (out[UNKNOWN] = [])).push(r.buf.slice(tagStart, r.pos));
      continue;
    }
    if (field.map) {
      const sub = r.fork();
      let k = defaultForType(field.map.key.type);
      let v = defaultForType(field.map.value.type);
      while (!sub.eof()) {
        const t = sub.uint32();
        const n = t >>> 3;
        const w = t & 7;
        if (n === 1)
          k = readSingle(sub, field.map.key.type);
        else if (n === 2)
          v = readSingle(sub, field.map.value.type);
        else
          sub.skip(w);
      }
      const obj = out[field.jsonName] ?? (out[field.jsonName] = {});
      obj[String(k)] = v;
      continue;
    }
    if (field.repeated) {
      const arr = out[field.jsonName] ?? (out[field.jsonName] = []);
      const packable = field.type.kind === "enum" || field.type.kind === "scalar" && field.type.scalar !== "string" && field.type.scalar !== "bytes";
      if (wire === WIRE_LEN && packable) {
        const sub = r.fork();
        while (!sub.eof()) {
          arr.push(field.type.kind === "enum" ? readEnum(sub, field.type.enum) : readScalar(sub, field.type.scalar));
        }
      } else {
        arr.push(readSingle(r, field.type));
      }
      continue;
    }
    if (wire !== expectedWire(field.type) && !(wire === WIRE_LEN && field.type.kind === "message")) {
      r.skip(wire);
      (out[UNKNOWN] ?? (out[UNKNOWN] = [])).push(r.buf.slice(tagStart, r.pos));
      continue;
    }
    if (field.oneofIndex >= 0) {
      for (const num of message.oneofs[field.oneofIndex].fieldNumbers) {
        const other = message.fieldByNumber.get(num);
        if (other.jsonName !== field.jsonName)
          delete out[other.jsonName];
      }
    }
    if (field.type.kind === "message") {
      const existing = out[field.jsonName];
      const into = existing && typeof existing === "object" ? existing : undefined;
      out[field.jsonName] = decode(field.type.message, r.fork(), into);
    } else {
      out[field.jsonName] = readSingle(r, field.type);
    }
  }
  return out;
}
function defaultForType(type) {
  if (type.kind === "scalar") {
    switch (type.scalar) {
      case "int64":
      case "uint64":
      case "sint64":
      case "fixed64":
      case "sfixed64":
        return 0n;
      case "bool":
        return false;
      case "string":
        return "";
      case "bytes":
        return new Uint8Array(0);
      default:
        return 0;
    }
  }
  if (type.kind === "enum")
    return type.enum.byNumber.get(0) ?? 0;
  return {};
}

// serialization/protobuf/writer.ts
class Writer {
  buf;
  len;
  view;
  constructor(capacity = 64) {
    this.buf = new Uint8Array(capacity);
    this.len = 0;
    this.view = new DataView(this.buf.buffer);
  }
  ensure(n) {
    const need = this.len + n;
    if (need <= this.buf.length)
      return;
    let cap = this.buf.length * 2;
    while (cap < need)
      cap *= 2;
    const next = new Uint8Array(cap);
    next.set(this.buf.subarray(0, this.len));
    this.buf = next;
    this.view = new DataView(this.buf.buffer);
  }
  finish() {
    return this.buf.slice(0, this.len);
  }
  get length() {
    return this.len;
  }
  uint32(value) {
    value = value >>> 0;
    this.ensure(5);
    while (value > 127) {
      this.buf[this.len++] = value & 127 | 128;
      value >>>= 7;
    }
    this.buf[this.len++] = value;
  }
  int32(value) {
    if (value < 0)
      this.varint64(BigInt.asUintN(64, BigInt(value)));
    else
      this.uint32(value);
  }
  sint32(value) {
    this.uint32((value << 1 ^ value >> 31) >>> 0);
  }
  varint64(value) {
    value = BigInt.asUintN(64, value);
    this.ensure(10);
    while (value > 0x7fn) {
      this.buf[this.len++] = Number(value & 0x7fn) | 128;
      value >>= 7n;
    }
    this.buf[this.len++] = Number(value);
  }
  sint64(value) {
    const v = BigInt.asIntN(64, value);
    this.varint64(v << 1n ^ v >> 63n);
  }
  bool(value) {
    this.ensure(1);
    this.buf[this.len++] = value ? 1 : 0;
  }
  tag(fieldNo, wireType) {
    this.uint32((fieldNo << 3 | wireType) >>> 0);
  }
  fixed32(value) {
    this.ensure(4);
    this.view.setUint32(this.len, value >>> 0, true);
    this.len += 4;
  }
  sfixed32(value) {
    this.ensure(4);
    this.view.setInt32(this.len, value | 0, true);
    this.len += 4;
  }
  float(value) {
    this.ensure(4);
    this.view.setFloat32(this.len, value, true);
    this.len += 4;
  }
  fixed64(value) {
    this.ensure(8);
    this.view.setBigUint64(this.len, BigInt.asUintN(64, value), true);
    this.len += 8;
  }
  sfixed64(value) {
    this.ensure(8);
    this.view.setBigInt64(this.len, BigInt.asIntN(64, value), true);
    this.len += 8;
  }
  double(value) {
    this.ensure(8);
    this.view.setFloat64(this.len, value, true);
    this.len += 8;
  }
  string(value) {
    const n = utf8Length(value);
    this.uint32(n);
    this.ensure(n);
    this.len = utf8Write(value, this.buf, this.len);
  }
  bytes(value) {
    this.uint32(value.length);
    this.ensure(value.length);
    this.buf.set(value, this.len);
    this.len += value.length;
  }
  raw(value) {
    this.ensure(value.length);
    this.buf.set(value, this.len);
    this.len += value.length;
  }
  lenDelimited(fieldNo, child) {
    this.tag(fieldNo, WIRE_LEN);
    const bytes = child.finish();
    this.uint32(bytes.length);
    this.raw(bytes);
  }
}

// serialization/protobuf/encode.ts
function writeScalarRaw(w, t, v) {
  switch (t) {
    case "double":
      w.double(v);
      break;
    case "float":
      w.float(v);
      break;
    case "int32":
      w.int32(v);
      break;
    case "int64":
      w.varint64(BigInt(v));
      break;
    case "uint32":
      w.uint32(v);
      break;
    case "uint64":
      w.varint64(BigInt(v));
      break;
    case "sint32":
      w.sint32(v);
      break;
    case "sint64":
      w.sint64(BigInt(v));
      break;
    case "fixed32":
      w.fixed32(v);
      break;
    case "fixed64":
      w.fixed64(BigInt(v));
      break;
    case "sfixed32":
      w.sfixed32(v);
      break;
    case "sfixed64":
      w.sfixed64(BigInt(v));
      break;
    case "bool":
      w.bool(v);
      break;
    case "string":
      w.string(v);
      break;
    case "bytes":
      w.bytes(v);
      break;
  }
}
function enumNumber(e, v) {
  if (typeof v === "number")
    return v;
  const n = e.byName.get(v);
  if (n === undefined)
    throw new Error(`protobuf: unknown enum value "${String(v)}" for ${e.fullName}`);
  return n;
}
function wireFor(type) {
  if (type.kind === "message")
    return 2;
  if (type.kind === "enum")
    return 0;
  switch (type.scalar) {
    case "string":
    case "bytes":
      return 2;
    case "double":
    case "fixed64":
    case "sfixed64":
      return 1;
    case "float":
    case "fixed32":
    case "sfixed32":
      return 5;
    default:
      return 0;
  }
}
function writeField(w, field, v) {
  const type = field.type;
  if (type.kind === "message") {
    const child = new Writer;
    encode(type.message, v, child);
    w.lenDelimited(field.number, child);
    return;
  }
  if (type.kind === "enum") {
    w.tag(field.number, 0);
    w.int32(enumNumber(type.enum, v));
    return;
  }
  w.tag(field.number, wireFor(type));
  writeScalarRaw(w, type.scalar, v);
}
function isDefault(type, v) {
  if (type.kind === "scalar") {
    switch (type.scalar) {
      case "int64":
      case "uint64":
      case "sint64":
      case "fixed64":
      case "sfixed64":
        return BigInt(v) === 0n;
      case "bool":
        return v === false;
      case "string":
        return v === "";
      case "bytes":
        return v.length === 0;
      default:
        return v === 0;
    }
  }
  if (type.kind === "enum") {
    const n = enumNumber(type.enum, v);
    return n === 0;
  }
  return false;
}
function mapKeyTyped(t, k) {
  switch (t) {
    case "string":
      return k;
    case "bool":
      return k === "true";
    case "int64":
    case "uint64":
    case "sint64":
    case "fixed64":
    case "sfixed64":
      return BigInt(k);
    default:
      return Number(k);
  }
}
function encode(message, value, w) {
  for (const field of message.fields) {
    const v = value[field.jsonName];
    if (field.map) {
      if (v == null)
        continue;
      const keyType = field.map.key.type;
      for (const [k, val] of Object.entries(v)) {
        const entry = new Writer;
        writeField(entry, field.map.key, mapKeyTyped(keyType.scalar, k));
        writeField(entry, field.map.value, val);
        w.lenDelimited(field.number, entry);
      }
      continue;
    }
    if (field.repeated) {
      if (!Array.isArray(v) || v.length === 0)
        continue;
      if (field.packed) {
        const child = new Writer;
        if (field.type.kind === "enum") {
          for (const e of v)
            child.int32(enumNumber(field.type.enum, e));
        } else {
          const scalar = field.type.scalar;
          for (const e of v)
            writeScalarRaw(child, scalar, e);
        }
        w.tag(field.number, WIRE_LEN);
        w.uint32(child.length);
        w.raw(child.finish());
      } else {
        for (const e of v)
          writeField(w, field, e);
      }
      continue;
    }
    if (v === undefined || v === null)
      continue;
    if (!field.explicitPresence && isDefault(field.type, v))
      continue;
    writeField(w, field, v);
  }
  const unknown = value[UNKNOWN];
  if (unknown)
    for (const raw of unknown)
      w.raw(raw);
}

// serialization/protobuf/wkt.ts
var WKT = {
  "google/protobuf/timestamp.proto": `
    syntax = "proto3"; package google.protobuf;
    message Timestamp { int64 seconds = 1; int32 nanos = 2; }
  `,
  "google/protobuf/duration.proto": `
    syntax = "proto3"; package google.protobuf;
    message Duration { int64 seconds = 1; int32 nanos = 2; }
  `,
  "google/protobuf/empty.proto": `
    syntax = "proto3"; package google.protobuf;
    message Empty {}
  `,
  "google/protobuf/field_mask.proto": `
    syntax = "proto3"; package google.protobuf;
    message FieldMask { repeated string paths = 1; }
  `,
  "google/protobuf/any.proto": `
    syntax = "proto3"; package google.protobuf;
    message Any { string type_url = 1; bytes value = 2; }
  `,
  "google/protobuf/wrappers.proto": `
    syntax = "proto3"; package google.protobuf;
    message DoubleValue { double value = 1; }
    message FloatValue { float value = 1; }
    message Int64Value { int64 value = 1; }
    message UInt64Value { uint64 value = 1; }
    message Int32Value { int32 value = 1; }
    message UInt32Value { uint32 value = 1; }
    message BoolValue { bool value = 1; }
    message StringValue { string value = 1; }
    message BytesValue { bytes value = 1; }
  `,
  "google/protobuf/struct.proto": `
    syntax = "proto3"; package google.protobuf;
    message Struct { map<string, Value> fields = 1; }
    message Value {
      oneof kind {
        NullValue null_value = 1;
        double number_value = 2;
        string string_value = 3;
        bool bool_value = 4;
        Struct struct_value = 5;
        ListValue list_value = 6;
      }
    }
    message ListValue { repeated Value values = 1; }
    enum NullValue { NULL_VALUE = 0; }
  `
};

// serialization/protobuf/schema.ts
class Schema {
  registry;
  constructor(proto, _opts = {}) {
    const sources = typeof proto === "string" ? { "__main__.proto": proto } : { ...proto };
    const parsed = [];
    const seen = new Set;
    const toParse = Object.keys(sources);
    while (toParse.length) {
      const name = toParse.shift();
      if (seen.has(name))
        continue;
      seen.add(name);
      const src = sources[name] ?? WKT[name];
      if (src == null)
        throw new Error(`protobuf: cannot resolve import "${name}"`);
      const pf = parseProto(src);
      parsed.push(pf);
      for (const imp of pf.imports)
        if (!seen.has(imp))
          toParse.push(imp);
    }
    this.registry = link(parsed);
  }
  parse(messageName, bytes) {
    const m = this.registry.messages.get(messageName);
    if (!m)
      throw new Error(`protobuf: unknown message "${messageName}"`);
    return decode(m, new Reader(bytes));
  }
  build(messageName, value) {
    const m = this.registry.messages.get(messageName);
    if (!m)
      throw new Error(`protobuf: unknown message "${messageName}"`);
    const w = new Writer;
    encode(m, value, w);
    return w.finish();
  }
}
var Protobuf = { Schema };

// serialization/index.ts
var ops = globalThis.__ops;
var {
  xml_parse,
  xml_validate,
  xml_build,
  yaml_parse,
  yaml_validate,
  yaml_build,
  toml_parse,
  toml_validate,
  toml_build,
  msgpack_parse,
  msgpack_validate,
  msgpack_build,
  xml_stream_new,
  xml_stream_push,
  xml_stream_close
} = ops;
function validateWith(fn, input, options = {}) {
  const result = fn(input);
  if (result === true)
    return options.detailed ? { valid: true } : true;
  return options.detailed ? { valid: false, error: result } : false;
}
var TOML = {
  validate: (toml, options) => validateWith(toml_validate, toml, options),
  parse: (toml) => toml_parse(toml),
  build: (obj) => toml_build(obj)
};
var YAML = {
  validate: (yaml, options) => validateWith(yaml_validate, yaml, options),
  parse: (yaml) => yaml_parse(yaml),
  build: (obj) => yaml_build(obj)
};
var MessagePack = {
  validate: (msgpack, options) => validateWith(msgpack_validate, msgpack, options),
  decode: (msgpack) => JSON.parse(msgpack_parse(msgpack)),
  encode: (obj) => msgpack_build(obj)
};

class JSONLDecoderStream extends TransformStream {
  onError;
  constructor(options = {}) {
    let buffer = "";
    const decoder = new TextDecoder;
    const skipInvalid = !!options.skipInvalid;
    let lineNumber = 0;
    let errorCallback = null;
    const emit = (controller, raw) => {
      const trimmed = raw.trim();
      if (!trimmed)
        return;
      try {
        controller.enqueue(JSON.parse(trimmed));
      } catch (err) {
        if (skipInvalid)
          errorCallback?.({ line: lineNumber, raw: trimmed, cause: err });
        else
          controller.error(new SyntaxError(`Invalid JSONL line ${lineNumber}: ${err.message}`));
      }
    };
    super({
      transform(chunk, controller) {
        const text = typeof chunk === "string" ? chunk : decoder.decode(chunk, { stream: true });
        buffer += text;
        const lines = buffer.split(`
`);
        buffer = lines.pop() ?? "";
        for (const line of lines) {
          lineNumber++;
          emit(controller, line);
        }
      },
      flush(controller) {
        if (buffer) {
          lineNumber++;
          emit(controller, buffer);
        }
      }
    });
    this.onError = (cb) => {
      errorCallback = cb;
    };
  }
}

class JSONLEncoderStream extends TransformStream {
  _writer = null;
  constructor() {
    super({
      transform(chunk, controller) {
        try {
          controller.enqueue(JSON.stringify(chunk) + `
`);
        } catch (err) {
          controller.error(new TypeError(`Cannot serialize to JSONL: ${err.message}`));
        }
      }
    });
  }
  pipeTo(destination, options) {
    return this.readable.pipeTo(destination, options);
  }
  write(chunk) {
    this._writer ??= this.writable.getWriter();
    return this._writer.write(chunk);
  }
  close() {
    return (this._writer ?? this.writable.getWriter()).close();
  }
}
var JSONL = { DecoderStream: JSONLDecoderStream, EncoderStream: JSONLEncoderStream };

class XMLDecoderStream extends TransformStream {
  constructor() {
    let streamId = null;
    super({
      start() {
        streamId = xml_stream_new();
      },
      transform(chunk, controller) {
        const text = typeof chunk === "string" ? chunk : new TextDecoder().decode(chunk);
        for (const obj of xml_stream_push(streamId, text))
          controller.enqueue(obj);
      },
      flush() {
        xml_stream_close(streamId);
      }
    });
  }
}
var XML = {
  validate: (xml, options) => validateWith(xml_validate, xml, options),
  parse: (xml) => xml_parse(xml),
  build: (obj) => xml_build(obj),
  DecoderStream: XMLDecoderStream
};
export {
  YAML,
  XML,
  TOML,
  Protobuf,
  MessagePack,
  JSONL
};
