//! Bakes the `esdev create` templates into the binary.
//!
//! **Embedded rather than fetched.** A scaffolder that downloads is a scaffolder
//! that can hand you something the binary was never tested against — and remote
//! module imports are a stated non-goal of this project, which a template
//! download would be by another name. Baked in, `esdev create` works offline, on
//! a locked-down machine, and always produces a project the `esdev` that wrote
//! it can build. The cost is a few tens of kilobytes of text.
//!
//! What is skipped is what a *running* template leaves behind — `node_modules`,
//! `dist`, a lockfile. Those are not the template: a scaffolded project resolves
//! and builds its own, and embedding an installed `node_modules` would put tens
//! of megabytes of somebody else's code in this binary.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// Directories and files never part of a template, whatever a developer's
/// working copy happens to hold.
const SKIPPED: &[&str] = &[
    "node_modules",
    "dist",
    "target",
    ".git",
    "bun.lock",
    "bun.lockb",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    ".DS_Store",
];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let templates = manifest.join("templates");
    println!("cargo:rerun-if-changed={}", templates.display());

    let mut names: Vec<String> = Vec::new();
    let mut generated = String::from(
        "// Generated by build.rs. The templates `esdev create` writes.\n\
         /// One file of a template: the path it is written to, and its bytes.\n\
         pub type TemplateFile = (&'static str, &'static [u8]);\n\
         /// A template: its name, and every file in it.\n\
         pub type Template = (&'static str, &'static [TemplateFile]);\n\
         /// Every template baked into this binary.\n\
         pub static TEMPLATES: &[Template] = &[\n",
    );

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&templates)
        .map(|read| read.flatten().map(|entry| entry.path()).collect())
        .unwrap_or_default();
    entries.sort();

    for template in entries.iter().filter(|path| path.is_dir()) {
        let name = template
            .file_name()
            .and_then(|n| n.to_str())
            .expect("a template directory name")
            .to_string();
        let mut files = Vec::new();
        collect(template, template, &mut files);
        files.sort();

        writeln!(generated, "    (\"{name}\", &[").expect("write");
        for (relative, absolute) in files {
            // `rerun-if-changed` on the directory covers additions and
            // removals; naming each file covers an edit to one, which some
            // platforms do not report as a change to its directory.
            println!("cargo:rerun-if-changed={}", absolute.display());
            writeln!(
                generated,
                "        ({:?}, include_bytes!({:?})),",
                relative,
                absolute.display().to_string()
            )
            .expect("write");
        }
        generated.push_str("    ]),\n");
        names.push(name);
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("templates.rs");
    std::fs::write(&out, generated).expect("write templates.rs");

    if names.is_empty() {
        println!(
            "cargo:warning=no templates found in {}",
            templates.display()
        );
    }
}

/// Every file under `dir`, as (path relative to the template root, absolute
/// path).
fn collect(root: &Path, dir: &Path, files: &mut Vec<(String, PathBuf)>) {
    let Ok(read) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in read.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        if SKIPPED.contains(&name.as_str()) {
            continue;
        }
        if path.is_dir() {
            collect(root, &path, files);
            continue;
        }
        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        // Always `/`, whatever wrote it: this string is a path the scaffolder
        // joins onto a destination, and on Windows a backslash in it would be
        // part of a filename rather than a separator.
        files.push((relative.to_string_lossy().replace('\\', "/"), path.clone()));
    }
}
