// Bundles `color` from @opentf/std into the embedded module
// crates/dev-cli/src/dom/std-color.js, which `runtime:dom/colors` imports for
// the 148 CSS colour names and the hex/rgb/hsl conversions behind
// `getComputedStyle(el).color`.
//
// Bundled with our own `esdev`, like crates/runtime/js: this file becomes part
// of a binary we ship, so the tool that produces it is one we ship too.
//
// It lands in `crates/dev-cli/src/dom/`, which only `esdev test --dom` loads —
// esrun's crate graph does not reach dev-cli, so nothing here can reach it.
// Run: tsr build
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const BANNER = "// @generated by `tsr build` in crates/dev-cli/js — do not edit by hand.\n";
const OUT = fileURLToPath(new URL("../src/dom/std-color.js", import.meta.url));
const ENTRY = fileURLToPath(new URL("./color.js", import.meta.url));
const LOCAL = fileURLToPath(new URL("../../../target/release/esdev", import.meta.url));

// To a temporary path first, then one write of the real file with its banner:
// an interrupted build must not leave a committed artifact without the comment
// CI checks for.
const TMP = `${OUT}.tmp`;
const esdev = existsSync(LOCAL) ? LOCAL : "esdev";
const built = spawnSync(esdev, ["build", ENTRY, `--out=${TMP}`, "--minify"], { stdio: "inherit" });
if (built.error || built.status !== 0) {
  rmSync(TMP, { force: true });
  console.error(
    built.error?.code === "ENOENT"
      ? "esdev not found — install it, or: cargo build --release -p es-runtime-dev-cli"
      : "esdev build failed",
  );
  process.exit(1);
}
writeFileSync(OUT, BANNER + readFileSync(TMP, "utf8"));
rmSync(TMP, { force: true });
console.log(`wrote ${OUT}`);
