#!/usr/bin/env bash
#
# Regenerates the site's benchmark data module from a real benchmark run.
#
# Runs bench/run.sh in machine mode (BENCH_JSON=1) and wraps its JSON output as
# an ES module the site imports directly. The numbers are therefore never typed
# by hand — this script is the only way the site data changes.
#
# Usage:  bench/gen-bench-data.sh            (uses auto-detected runtimes)
#         ESRUN=/path/to/esrun bench/gen-bench-data.sh
set -euo pipefail
cd "$(dirname "$0")"

OUT="../site/src/benchmarks.js"
TMP1="$(mktemp)"
TMP2="$(mktemp)"
TMP3="$(mktemp)"
TMP_COMBINED="$(mktemp)"
trap 'rm -f "$TMP1" "$TMP2" "$TMP3" "$TMP_COMBINED"' EXIT

if [ $# -gt 0 ]; then
  # Partial update mode
  echo "Running partial update for: $*"
  WORKLOADS="$*" BENCH_JSON=1 bash run.sh > "$TMP1"
  node -e 'JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"))' "$TMP1"

  # Merge with existing benchmarks.js
  node -e '
    const fs = require("fs");
    let existingStr = fs.readFileSync(process.argv[1], "utf8");
    // Strip the "export default " and comments
    existingStr = existingStr.replace(/^\/\/.*\n/gm, "").replace(/^export default /, "");
    const existing = JSON.parse(existingStr);
    const updated = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
    // Deep merge runtime results for the targeted workloads
    for (const [workload, runtimes] of Object.entries(updated)) {
      if (!existing[workload]) existing[workload] = {};
      Object.assign(existing[workload], runtimes);
    }
    fs.writeFileSync(process.argv[3], JSON.stringify(existing, null, 2));
  ' "$OUT" "$TMP1" "$TMP_COMBINED"

else
  # Full suite mode
  # Capture the machine-readable runs first
  BENCH_JSON=1 bash run.sh > "$TMP1"
  node -e 'JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"))' "$TMP1"

  # Run rps.sh for Hono RPS
  SERVER=scripts/hono.js BENCH_JSON=1 bash rps.sh > "$TMP2"
  node -e 'JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"))' "$TMP2"

  # WebSocket chat broadcast C-sweep (server + client fan-out msg/s)
  BENCH_JSON=1 bash websocket-chat/run-chat.sh > "$TMP3"
  node -e 'JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"))' "$TMP3"

  # Merge the JSON objects
  node -e '
    const fs = require("fs");
    const t1 = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    const t2 = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
    const t3 = JSON.parse(fs.readFileSync(process.argv[3], "utf8"));
    const merged = Object.assign({}, t1, t2, t3);
    fs.writeFileSync(process.argv[4], JSON.stringify(merged, null, 2));
  ' "$TMP1" "$TMP2" "$TMP3" "$TMP_COMBINED"
fi

{
  echo "// AUTO-GENERATED by bench/gen-bench-data.sh from a real bench/run.sh run."
  echo "// Do not edit by hand — regenerate with: bench/gen-bench-data.sh"
  printf 'export default '
  cat "$TMP_COMBINED"
} > "$OUT"

echo "wrote $OUT" >&2
