// Bundles serialization/index.ts into the embedded runtime module
// crates/runtime/src/runtime_modules/serialization.js. Run: bun run build
const BANNER = "// @generated by `bun run build` in crates/runtime/js — do not edit by hand.\n";
const OUT = new URL("../src/runtime_modules/serialization.js", import.meta.url);

const result = await Bun.build({
  entrypoints: [new URL("./serialization/index.ts", import.meta.url).pathname],
  format: "esm",
  target: "node",
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const code = await result.outputs[0].text();
await Bun.write(OUT, BANNER + code);
console.log("wrote", OUT.pathname, `(${(BANNER.length + code.length)} bytes)`);
