// Bundles serialization/index.ts into the embedded runtime module
// crates/runtime/src/runtime_modules/serialization.js.
//
// Built with our own `esdev`, not a third-party bundler: this file becomes part
// of the runtime, so the tool that produces it is the one we ship. Run: tsr build
//
// `esdev` is found on PATH (the installer puts it in ~/.es-runtime/bin), then in
// this repo's target/release — so a contributor who has built it but not
// installed it does not have to install it first.
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const BANNER = "// @generated by `tsr build` in crates/runtime/js — do not edit by hand.\n";
const OUT = fileURLToPath(new URL("../src/runtime_modules/serialization.js", import.meta.url));
const ENTRY = fileURLToPath(new URL("./serialization/index.ts", import.meta.url));
const LOCAL = fileURLToPath(new URL("../../../target/release/esdev", import.meta.url));

// Bundle to a temporary path, then write the real file once, banner included.
// Writing OUT directly and prepending the banner afterwards leaves a window
// where the committed artifact exists without it — interrupt the build there
// (a closed pipe is enough) and CI's drift check fails on a missing comment.
const TMP = `${OUT}.tmp`;
const esdev = existsSync(LOCAL) ? LOCAL : "esdev";
const built = spawnSync(esdev, ["build", ENTRY, `--out=${TMP}`], { stdio: "inherit" });
if (built.error || built.status !== 0) {
  rmSync(TMP, { force: true });
  console.error(
    built.error?.code === "ENOENT"
      ? "esdev not found — install it, or: cargo build --release -p es-runtime-dev-cli"
      : "esdev build failed",
  );
  process.exit(1);
}

// The banner marks the file as generated for anyone who opens it in the Rust
// tree, where nothing else says where it came from.
const code = BANNER + readFileSync(TMP, "utf8");
rmSync(TMP, { force: true });
writeFileSync(OUT, code);
console.log(`wrote ${OUT} (${code.length} bytes)`);
