// Bundles serialization/index.ts into the embedded runtime module
// crates/runtime/src/runtime_modules/serialization.js.
//
// Built with our own `esdev`, not a third-party bundler: this file becomes part
// of the runtime, so the tool that produces it is the one we ship. Run: tsr build
//
// `esdev` is found on PATH (the installer puts it in ~/.es-runtime/bin), then in
// this repo's target/release — so a contributor who has built it but not
// installed it does not have to install it first.
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const BANNER = "// @generated by `tsr build` in crates/runtime/js — do not edit by hand.\n";
const OUT = fileURLToPath(new URL("../src/runtime_modules/serialization.js", import.meta.url));
const ENTRY = fileURLToPath(new URL("./serialization/index.ts", import.meta.url));
const LOCAL = fileURLToPath(new URL("../../../target/release/esdev", import.meta.url));

const esdev = existsSync(LOCAL) ? LOCAL : "esdev";
const built = spawnSync(esdev, ["build", ENTRY, `--out=${OUT}`], { stdio: "inherit" });
if (built.error || built.status !== 0) {
  console.error(
    built.error?.code === "ENOENT"
      ? "esdev not found — install it, or: cargo build --release -p es-runtime-dev-cli"
      : "esdev build failed",
  );
  process.exit(1);
}

// The banner marks the file as generated for anyone who opens it in the Rust
// tree, where nothing else says where it came from.
const code = readFileSync(OUT, "utf8");
if (!code.startsWith(BANNER)) writeFileSync(OUT, BANNER + code);
console.log(`wrote ${OUT} (${BANNER.length + code.length} bytes)`);
