// What this repo currently builds, from src/versions.js — generated by
// scripts/site-versions.mjs out of the crates' Cargo.toml, so a page cannot go
// on naming a version that was released three tags ago.
//
// `esrun` also has the navbar badge (otfw.config.js reads the same module).
// `esdev` has no such slot and is released on its own tag at its own pace, so
// anywhere the docs pin or name a version, they need to name esdev's too.
//
// One component per file: the compiler emits a module's default export only, so
// a named export here is missing by the time a page imports it.
import versions from "../src/versions.js";

export default function Versions() {
  return (
    <ul className="mt-2 grid gap-1 font-mono text-[12px] sm:grid-cols-2">
      <li>
        <span className="text-brand-700 dark:text-brand-400">esrun</span>{" "}
        <span className="text-zinc-500 dark:text-zinc-400">{versions.esrun}</span>
      </li>
      <li>
        <span className="text-brand-700 dark:text-brand-400">esdev</span>{" "}
        <span className="text-zinc-500 dark:text-zinc-400">{versions.esdev}</span>
      </li>
    </ul>
  );
}
