// Generates the CSS value table `runtime:dom/css` validates against, by asking
// Chrome about every property this DOM knows.
//
// The alternative is a hand-written guess at each property's grammar, which is
// what this replaces: a table of "which properties take a bare number" was
// wrong about `cx`, then about `transition-duration`, and each correction was
// another intuition. Chrome is the oracle everywhere else in this directory, so
// it is the oracle here too, and the table is regenerated rather than reasoned
// about.
//
// Per property it records, from `CSS.supports` and a declaration Chrome keeps:
//
//   * which *kinds* of value it accepts — a bare number, a length, a
//     percentage, a time, an angle, a resolution, a frequency, a flex — and
//     whether each may be negative,
//   * what a bare `0` serializes as, which is `0px` for a length, `0` for a
//     number, `0 / 1` for `aspect-ratio`, and nothing at all where zero is not
//     a value the property takes.
//
//   deno run --allow-env --allow-net --allow-read --allow-run --allow-sys \
//     --allow-write --config=wpt/dom-matrix/deno.json wpt/dom-matrix/css-table.js [--check]
import puppeteer from "puppeteer-core";

const root = new URL("../../", import.meta.url);
const source = new URL("crates/dev-cli/src/dom/css.js", root);
const output = new URL("crates/dev-cli/src/dom/css-table.js", root);
const chrome = Deno.args.find((argument) => argument.startsWith("--chrome="))?.slice("--chrome=".length)
  ?? "/usr/bin/google-chrome";
const check = Deno.args.includes("--check");

// The kinds a token can be, each with the probe that decides it. `1` and `-1`
// are the bare numbers; the rest carry a unit from their family.
const KINDS = [
  ["number", "1", "-1"],
  ["length", "1px", "-1px"],
  ["percentage", "50%", "-50%"],
  ["time", "1s", "-1s"],
  ["angle", "45deg", "-45deg"],
  ["resolution", "1dppx", "-1dppx"],
  ["frequency", "1khz", "-1khz"],
  ["flex", "1fr", "-1fr"],
];

const properties = [...(await Deno.readTextFile(source))
  .match(/const PROPERTIES = new Set\(`([\s\S]*?)`/)[1]
  .trim()
  .matchAll(/\S+/g)].map((match) => match[0]);

const browser = await puppeteer.launch({ executablePath: chrome, headless: true });
const table = await (async () => {
  const tab = await browser.newPage();
  // A document in standards mode: quirks mode accepts unitless lengths, which
  // would make every length property look as if it took a number.
  await tab.setContent("<!doctype html><html><body></body></html>");
  return tab.evaluate(
    (properties, kinds) => {
      const element = document.createElement("div");
      const found = {};
      // Three shapes per kind, because a property may not take one value on its
      // own: `box-shadow` needs two lengths before it accepts any, and
      // `counter-reset` wants a name in front of its number. A kind counts as
      // accepted if any shape is.
      const shapes = (value) => [value, `${value} ${value}`, `probe ${value}`];
      const accepted = (property, value) => shapes(value).some((shape) => CSS.supports(property, shape));
      for (const property of properties) {
        const accepts = [];
        for (const [kind, positive, negative] of kinds) {
          const yes = accepted(property, positive);
          const signed = accepted(property, negative);
          if (yes || signed) accepts.push(signed ? `${kind}±` : kind);
        }
        element.style.setProperty(property, "0");
        const zero = element.style.getPropertyValue(property);
        element.style.removeProperty(property);
        found[property] = { accepts, zero };
      }
      return found;
    },
    properties,
    KINDS,
  );
})();
await browser.close();

// One line per property, sorted, so a regeneration that changes one answer shows
// as one changed line.
const rows = Object.entries(table)
  .sort(([left], [right]) => (left < right ? -1 : 1))
  .map(([property, { accepts, zero }]) => `  ["${property}", "${accepts.join(" ")}", ${JSON.stringify(zero)}],`);

const text = `// @generated by \`tsr gen:css-table\` from Chrome — do not edit by hand.
//
// Per property: the value kinds it accepts (a trailing \`±\` means negatives are
// accepted too) and what a bare \`0\` serializes as. See
// \`wpt/dom-matrix/css-table.js\` for how this is produced and why.
export const CSS_VALUE_TABLE = [
${rows.join("\n")}
];
`;

if (check) {
  const current = await Deno.readTextFile(output).catch(() => null);
  if (current !== text) {
    console.error("crates/dev-cli/src/dom/css-table.js no longer matches Chrome — run `tsr gen:css-table`.");
    Deno.exit(1);
  }
  console.log(`the CSS value table matches Chrome for ${properties.length} properties`);
} else {
  await Deno.writeTextFile(output, text);
  console.log(`wrote crates/dev-cli/src/dom/css-table.js for ${properties.length} properties`);
}
